//! Reading a full generated STEP file, not a hand-written one.
//!
//! `part21_parse.rs` and `part21_round_trip.rs` exercise the grammar with
//! small literal strings crafted to hit specific syntax cases. Those are
//! deliberate and precise, but nothing in this crate confirms that L1 also
//! reads a file of realistic size and shape. `../fixtures/step/box.step` is
//! generated by `../fixtures/step/generate_box.py` — see that script to
//! regenerate or extend it.

use ngk::exchange::step::part21::{exchange_to_string, parse_exchange};

const BOX_STEP: &str = include_str!("../fixtures/step/box.step");

#[test]
fn a_generated_step_file_parses() {
    let exchange = parse_exchange(BOX_STEP).expect("the fixture should parse");

    assert!(
        !exchange.instances().is_empty(),
        "a box fixture should produce more than zero instances",
    );
}

#[test]
fn a_generated_step_file_survives_a_round_trip() {
    let first = parse_exchange(BOX_STEP).expect("the fixture should parse");
    let written = exchange_to_string(&first).expect("the parsed exchange should write");
    let second = parse_exchange(&written).expect("written text should parse");

    assert_eq!(
        first.instances().len(),
        second.instances().len(),
        "the instance count changed across the round trip",
    );
    for (before, after) in first.instances().iter().zip(second.instances()) {
        assert_eq!(before.id, after.id);
        assert_eq!(
            before.records, after.records,
            "instance {} changed across the round trip",
            before.id,
        );
    }
}
