from typing import Optional

def block(x: float, y: float, z: float) -> Solid: ...

class Solid:
    @property
    def key(self) -> str: ...
    @property
    def outer_shell(self) -> Shell: ...
    @property
    def shells(self) -> list[Shell]: ...
    @property
    def face_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    def faces(self) -> list[Face]: ...

class Shell:
    @property
    def dart_id(self) -> int: ...
    def faces(self) -> list[Face]: ...

class Face:
    @property
    def key(self) -> str: ...
    @property
    def surface(self) -> Surface: ...
    @property
    def outer_loop(self) -> Loop: ...
    @property
    def inner_loops(self) -> list[Loop]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Loop:
    @property
    def dart_id(self) -> int: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Edge:
    @property
    def dart_id(self) -> int: ...
    @property
    def start(self) -> Vertex: ...
    @property
    def end(self) -> Vertex: ...
    @property
    def length(self) -> Optional[float]: ...
    @property
    def curve(self) -> Optional[Curve]: ...
    def vertices(self) -> list[Vertex]: ...

class Vertex:
    @property
    def dart_id(self) -> int: ...
    @property
    def point(self) -> Optional[Point3]: ...
    def edges(self) -> list[Edge]: ...

class Point3:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

class Vector3:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

Curve = Line | Circle | NurbsCurve
Surface = Plane | Cylinder | RuledSurface | SurfaceOfRevolution | NurbsSurface

class Line:
    @property
    def start(self) -> Point3: ...
    @property
    def end(self) -> Point3: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, t: float) -> Point3: ...

class Circle:
    @property
    def plane(self) -> Plane: ...
    @property
    def radius(self) -> float: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, t: float) -> Point3: ...

class NurbsCurve:
    @property
    def degree(self) -> int: ...
    @property
    def domain(self) -> tuple[float, float]: ...
    @property
    def knots(self) -> list[float]: ...
    @property
    def control_points(self) -> list[tuple[Point3, float]]: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, u: float) -> Point3: ...

class Plane:
    @property
    def origin(self) -> Point3: ...
    @property
    def x_dir(self) -> Vector3: ...
    @property
    def y_dir(self) -> Vector3: ...
    @property
    def normal(self) -> Vector3: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class Cylinder:
    @property
    def origin(self) -> Point3: ...
    @property
    def x_dir(self) -> Vector3: ...
    @property
    def axis(self) -> Vector3: ...
    @property
    def radius(self) -> float: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class RuledSurface:
    @property
    def curve(self) -> Curve: ...
    @property
    def direction(self) -> Vector3: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class SurfaceOfRevolution:
    @property
    def curve(self) -> Curve: ...
    @property
    def origin(self) -> Point3: ...
    @property
    def axis(self) -> Vector3: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class NurbsSurface:
    @property
    def degree_u(self) -> int: ...
    @property
    def degree_v(self) -> int: ...
    @property
    def domain_u(self) -> tuple[float, float]: ...
    @property
    def domain_v(self) -> tuple[float, float]: ...
    @property
    def knots_u(self) -> list[float]: ...
    @property
    def knots_v(self) -> list[float]: ...
    @property
    def control_points(self) -> list[list[tuple[Point3, float]]]: ...
    @property
    def kind(self) -> str: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

