from ..geometry import Point
from ..topology import Edge, Face, Profile, Sheet, Solid

class MeasuredProperties:
    @property
    def amount(self) -> float: ...
    @property
    def centroid(self) -> Point: ...
    @property
    def inertia(self) -> tuple[float, float, float, float, float, float, float, float, float]: ...

def edge_properties(value: Edge) -> MeasuredProperties: ...
def profile_properties(value: Profile) -> MeasuredProperties: ...
def face_properties(value: Face) -> MeasuredProperties: ...
def sheet_properties(value: Sheet) -> MeasuredProperties: ...
def solid_properties(value: Solid) -> MeasuredProperties: ...
