use std::sync::Arc;

use thiserror::Error;

use crate::geometry::{Curve, Curve2, Point3, Surface};
use crate::topology::closed::{Closeable, Closed};
use crate::topology::edge::Edge;
use crate::topology::face::Face;
use crate::topology::gmap::{Dart, Dim, GMAP_INVOLUTION_COUNT, GMap};
use crate::topology::payload::{Payload, StandardPayload};
use crate::topology::profile::{Loop, Profile};
use crate::topology::shape_keys::{EdgeKey, FaceKey, ProfileKey, SheetKey, SolidKey, VertexKey};
use crate::topology::sheet::{Sheet, ShellRef};
use crate::topology::solid::Solid;
use crate::topology::vertex::Vertex;

/// Errors returned by the language-neutral exploration API.
#[derive(Debug, Error)]
pub(crate) enum ExploreError {
    /// A dimension or involution index was outside the supported range.
    #[error("invalid dimension {dimension}; expected a value from 0 through {max}")]
    InvalidDimension { dimension: usize, max: usize },
    /// A dart id did not address a dart in the map.
    #[error("invalid dart {dart}; map contains {dart_count} darts")]
    InvalidDart { dart: usize, dart_count: usize },
    /// Incidence requires two different cell dimensions.
    #[error("incident cells require different dimensions, got {dimension} twice")]
    SameDimension { dimension: usize },
    /// A stored handle could no longer be resolved in its immutable map.
    #[error("missing {kind} for {locator}")]
    MissingEntity { kind: &'static str, locator: String },
    /// Serde could not encode or decode the complete map.
    #[error("failed to serialize or deserialize GMap: {0}")]
    Serde(#[from] serde_json::Error),
}

/// Immutable shared ownership of a GMap used by language binding objects.
pub(crate) struct SharedGMap<P: Payload = StandardPayload> {
    map: Arc<GMap<P>>,
}

impl<P: Payload> Clone for SharedGMap<P> {
    fn clone(&self) -> Self {
        Self {
            map: Arc::clone(&self.map),
        }
    }
}

impl<P: Payload> SharedGMap<P> {
    /// Wraps an owned map in immutable shared ownership.
    pub(crate) fn from_map(map: GMap<P>) -> Self {
        Self { map: Arc::new(map) }
    }

    /// Returns the underlying read-only map.
    pub(crate) fn map(&self) -> &GMap<P> {
        self.map.as_ref()
    }

    /// Returns an identity token unique to this in-memory map instance.
    #[cfg(feature = "python")]
    pub(crate) fn identity(&self) -> usize {
        Arc::as_ptr(&self.map) as usize
    }

    /// Returns whether both wrappers share the exact same map instance.
    pub(crate) fn ptr_eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.map, &other.map)
    }

    /// Returns the highest supported cell dimension.
    pub(crate) fn dimension(&self) -> usize {
        GMAP_INVOLUTION_COUNT - 1
    }

    /// Returns the number of alpha involutions.
    pub(crate) fn involution_count(&self) -> usize {
        GMAP_INVOLUTION_COUNT
    }

    /// Returns the number of addressable darts.
    pub(crate) fn dart_count(&self) -> usize {
        self.map.dart_count()
    }

    /// Returns all dart ids.
    pub(crate) fn darts(&self) -> Vec<usize> {
        self.map.darts().map(|dart| dart.id()).collect()
    }

    /// Evaluates one alpha involution with checked binding inputs.
    pub(crate) fn alpha(&self, dimension: usize, dart: usize) -> Result<usize, ExploreError> {
        let dimension = self.checked_dimension(dimension)?;
        let dart = self.checked_dart(dart)?;
        Ok(self.map.alpha(dimension, dart).id())
    }

    /// Reports whether a dart is free on one alpha involution.
    pub(crate) fn is_free(&self, dimension: usize, dart: usize) -> Result<bool, ExploreError> {
        let dimension = self.checked_dimension(dimension)?;
        let dart = self.checked_dart(dart)?;
        Ok(self.map.is_free(dart, dimension))
    }

    /// Returns the orbit generated by the requested alpha involutions.
    pub(crate) fn orbit(
        &self,
        dart: usize,
        involutions: Vec<usize>,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        for &involution in &involutions {
            self.checked_dimension(involution)?;
        }
        Ok(self
            .map
            .orbit(dart, involutions)
            .map(|dart| dart.id())
            .collect())
    }

    /// Returns one representative dart for every cell of a dimension.
    pub(crate) fn cells(&self, dimension: usize) -> Result<Vec<usize>, ExploreError> {
        let dimension = self.checked_dimension(dimension)?;
        Ok(self
            .map
            .cells(dimension)
            .map(|dart| self.map.cell_representative(dart, dimension).id())
            .collect())
    }

    /// Returns every dart in the requested cell.
    pub(crate) fn cell_darts(
        &self,
        dart: usize,
        dimension: usize,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let dimension = self.checked_dimension(dimension)?;
        Ok(self
            .map
            .orbit(dart, self.map.orbit_indices(dimension))
            .map(|dart| dart.id())
            .collect())
    }

    /// Returns the canonical representative dart of a cell.
    pub(crate) fn cell_representative(
        &self,
        dart: usize,
        dimension: usize,
    ) -> Result<usize, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let dimension = self.checked_dimension(dimension)?;
        Ok(self.map.cell_representative(dart, dimension).id())
    }

    /// Returns canonical representatives of cells incident to a container cell.
    pub(crate) fn incident_cells(
        &self,
        dart: usize,
        container_dimension: usize,
        target_dimension: usize,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let container = self.checked_dimension(container_dimension)?;
        let target = self.checked_dimension(target_dimension)?;
        if container == target {
            return Err(ExploreError::SameDimension {
                dimension: container_dimension,
            });
        }
        Ok(self
            .map
            .incident_cells(dart, container, target)
            .map(|dart| self.map.cell_representative(dart, target).id())
            .collect())
    }

    /// Returns canonical representatives of adjacent cells of a dimension.
    pub(crate) fn adjacent_cells(
        &self,
        dart: usize,
        dimension: usize,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let dimension = self.checked_dimension(dimension)?;
        Ok(self
            .map
            .adjacent_cells(dart, dimension)
            .map(|dart| self.map.cell_representative(dart, dimension).id())
            .collect())
    }

    /// Returns every registered vertex in default orientation.
    pub(crate) fn vertices(&self) -> Vec<SharedVertex<P>> {
        self.map
            .iter_vertices()
            .map(|(key, _)| SharedVertex::from_view(self.clone(), self.map.vertex_unchecked(key)))
            .collect()
    }

    /// Returns every registered edge in default orientation.
    pub(crate) fn edges(&self) -> Vec<SharedEdge<P>> {
        self.map
            .iter_edges()
            .map(|(key, _)| SharedEdge::from_view(self.clone(), self.map.edge_unchecked(key)))
            .collect()
    }

    /// Returns every registered profile in default orientation.
    pub(crate) fn profiles(&self) -> Vec<SharedProfile<P>> {
        self.map
            .iter_profiles()
            .map(|(key, _)| SharedProfile::from_view(self.clone(), self.map.profile_unchecked(key)))
            .collect()
    }

    /// Returns every registered face in default orientation.
    pub(crate) fn faces(&self) -> Vec<SharedFace<P>> {
        self.map
            .iter_faces()
            .map(|(key, _)| SharedFace::from_view(self.clone(), self.map.face_unchecked(key)))
            .collect()
    }

    /// Returns every registered sheet in default orientation.
    pub(crate) fn sheets(&self) -> Vec<SharedSheet<P>> {
        self.map
            .iter_sheets()
            .map(|(key, _)| SharedSheet::from_view(self.clone(), self.map.sheet_unchecked(key)))
            .collect()
    }

    /// Returns every registered solid in default orientation.
    pub(crate) fn solids(&self) -> Vec<SharedSolid<P>> {
        self.map
            .iter_solids()
            .map(|(key, _)| SharedSolid::from_view(self.clone(), self.map.solid_unchecked(key)))
            .collect()
    }

    /// Resolves the registered vertex containing a dart.
    pub(crate) fn vertex_at(&self, dart: usize) -> Result<Option<SharedVertex<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Vertex::from_dart(self.map(), dart)
            .map(|view| SharedVertex::from_view(self.clone(), view)))
    }

    /// Resolves the registered edge containing a dart.
    pub(crate) fn edge_at(&self, dart: usize) -> Result<Option<SharedEdge<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Edge::from_dart(self.map(), dart).map(|view| SharedEdge::from_view(self.clone(), view)))
    }

    /// Resolves the registered profile containing a dart.
    pub(crate) fn profile_at(&self, dart: usize) -> Result<Option<SharedProfile<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Profile::from_dart(self.map(), dart)
            .map(|view| SharedProfile::from_view(self.clone(), view)))
    }

    /// Resolves the registered face containing a dart.
    pub(crate) fn face_at(&self, dart: usize) -> Result<Option<SharedFace<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Face::from_dart(self.map(), dart).map(|view| SharedFace::from_view(self.clone(), view)))
    }

    /// Resolves the registered sheet containing a dart.
    pub(crate) fn sheet_at(&self, dart: usize) -> Result<Option<SharedSheet<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Sheet::from_dart(self.map(), dart)
            .map(|view| SharedSheet::from_view(self.clone(), view)))
    }

    /// Resolves the registered solid containing a dart.
    pub(crate) fn solid_at(&self, dart: usize) -> Result<Option<SharedSolid<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Solid::from_dart(self.map(), dart)
            .map(|view| SharedSolid::from_view(self.clone(), view)))
    }

    /// Resolves a registered edge from its stable key.
    pub(crate) fn edge_by_key(&self, key: EdgeKey) -> Option<SharedEdge<P>> {
        self.map
            .edge(key)
            .map(|view| SharedEdge::from_view(self.clone(), view))
    }

    /// Resolves a registered profile from its stable key.
    pub(crate) fn profile_by_key(&self, key: ProfileKey) -> Option<SharedProfile<P>> {
        self.map
            .profile(key)
            .map(|view| SharedProfile::from_view(self.clone(), view))
    }

    /// Resolves a registered face from its stable key.
    pub(crate) fn face_by_key(&self, key: FaceKey) -> Option<SharedFace<P>> {
        self.map
            .face(key)
            .map(|view| SharedFace::from_view(self.clone(), view))
    }

    /// Resolves a registered solid from its stable key.
    pub(crate) fn solid_by_key(&self, key: SolidKey) -> Option<SharedSolid<P>> {
        self.map
            .solid(key)
            .map(|view| SharedSolid::from_view(self.clone(), view))
    }

    fn checked_dimension(&self, dimension: usize) -> Result<Dim, ExploreError> {
        if dimension >= GMAP_INVOLUTION_COUNT {
            return Err(ExploreError::InvalidDimension {
                dimension,
                max: GMAP_INVOLUTION_COUNT - 1,
            });
        }
        Ok(Dim::from_index(dimension))
    }

    fn checked_dart(&self, dart: usize) -> Result<Dart, ExploreError> {
        if dart >= self.map.dart_count() {
            return Err(ExploreError::InvalidDart {
                dart,
                dart_count: self.map.dart_count(),
            });
        }
        Ok(Dart::new(dart))
    }
}

impl SharedGMap<StandardPayload> {
    /// Serializes the complete immutable map as JSON.
    pub(crate) fn serialize(&self) -> Result<String, ExploreError> {
        Ok(serde_json::to_string(self.map())?)
    }

    /// Deserializes a complete standard-payload map without validation.
    pub(crate) fn deserialize(serialized: &str) -> Result<Self, ExploreError> {
        let map = serde_json::from_str(serialized)?;
        Ok(Self::from_map(map))
    }
}

fn missing(kind: &'static str, locator: impl ToString) -> ExploreError {
    ExploreError::MissingEntity {
        kind,
        locator: locator.to_string(),
    }
}

macro_rules! shared_identity {
    ($type:ident, $key:ty) => {
        impl<P: Payload> $type<P> {
            /// Returns this handle's shared map.
            pub(crate) fn gmap(&self) -> SharedGMap<P> {
                self.map.clone()
            }

            /// Returns its opaque stable key.
            pub(crate) fn key(&self) -> $key {
                self.key
            }

            /// Returns its contextual dart id.
            pub(crate) fn dart_id(&self) -> usize {
                self.dart.id()
            }

            /// Returns whether both handles identify the same entity in the same map.
            pub(crate) fn same_entity(&self, other: &Self) -> bool {
                self.map.ptr_eq(&other.map) && self.key == other.key
            }
        }

        impl<P: Payload> PartialEq for $type<P> {
            fn eq(&self, other: &Self) -> bool {
                self.same_entity(other)
            }
        }

        impl<P: Payload> Eq for $type<P> {}
    };
}

/// Owned read-only vertex handle.
#[derive(Clone)]
pub(crate) struct SharedVertex<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: VertexKey,
    dart: Dart,
}

shared_identity!(SharedVertex, VertexKey);

impl<P: Payload> SharedVertex<P> {
    fn from_view(map: SharedGMap<P>, view: Vertex<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart,
        }
    }

    fn view(&self) -> Result<Vertex<'_, P>, ExploreError> {
        Vertex::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("vertex", self.dart.id()))
    }

    /// Returns the stored point geometry.
    pub(crate) fn point(&self) -> Result<Option<Point3>, ExploreError> {
        Ok(self.view()?.point().copied())
    }

    /// Returns incident edges.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns incident faces.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns incident sheets.
    pub(crate) fn sheets(&self) -> Result<Vec<SharedSheet<P>>, ExploreError> {
        Ok(self
            .view()?
            .sheets()
            .into_iter()
            .map(|view| SharedSheet::from_view(self.map.clone(), view))
            .collect())
    }
}

/// Owned read-only edge handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedEdge<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: EdgeKey,
    dart: Dart,
}

shared_identity!(SharedEdge, EdgeKey);

impl<P: Payload> SharedEdge<P> {
    fn from_view(map: SharedGMap<P>, view: Edge<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<Edge<'_, P>, ExploreError> {
        Edge::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("edge", self.dart.id()))
    }

    /// Returns all darts in this edge cell.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns the oriented start vertex.
    pub(crate) fn start(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.map.clone(),
            self.view()?.start(),
        ))
    }

    /// Returns the oriented end vertex.
    pub(crate) fn end(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.map.clone(),
            self.view()?.end(),
        ))
    }

    /// Returns distinct incident vertices.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns incident faces.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns incident sheets.
    pub(crate) fn sheets(&self) -> Result<Vec<SharedSheet<P>>, ExploreError> {
        Ok(self
            .view()?
            .sheets()
            .into_iter()
            .map(|view| SharedSheet::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns a clone of the attached curve.
    pub(crate) fn curve(&self) -> Result<Option<Curve>, ExploreError> {
        Ok(self.view()?.curve().cloned())
    }

    /// Returns the geometric edge length when geometry is available.
    pub(crate) fn length(&self) -> Result<Option<f64>, ExploreError> {
        Ok(self.view()?.length())
    }

    /// Returns the same edge in the opposite orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.map.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only profile handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedProfile<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: ProfileKey,
    dart: Dart,
}

shared_identity!(SharedProfile, ProfileKey);

impl<P: Payload> SharedProfile<P> {
    fn from_view(map: SharedGMap<P>, view: Profile<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart,
        }
    }

    fn view(&self) -> Result<Profile<'_, P>, ExploreError> {
        Profile::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("profile", self.dart.id()))
    }

    /// Returns traversal-order dart ids.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns whether this profile is closed.
    pub(crate) fn is_closed(&self) -> Result<bool, ExploreError> {
        Ok(self.view()?.is_closed())
    }

    /// Returns the first traversal vertex.
    pub(crate) fn start(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.map.clone(),
            self.view()?.start(),
        ))
    }

    /// Returns the final traversal vertex.
    pub(crate) fn end(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.map.clone(),
            self.view()?.end(),
        ))
    }

    /// Returns traversal-order edges.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns traversal-order vertices.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns the same profile in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.map.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only closed profile handle.
#[derive(Clone)]
pub(crate) struct SharedLoop<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: ProfileKey,
    dart: Dart,
}

shared_identity!(SharedLoop, ProfileKey);

impl<P: Payload> SharedLoop<P> {
    fn from_view(map: SharedGMap<P>, view: Loop<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart,
        }
    }

    fn view(&self) -> Result<Loop<'_, P>, ExploreError> {
        let profile = Profile::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("loop", self.dart.id()))?;
        Ok(Closed::new_unchecked(profile))
    }

    /// Returns traversal-order dart ids.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns traversal-order edges.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns traversal-order vertices.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns the same loop in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.map.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only face handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedFace<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: FaceKey,
    dart: Dart,
}

shared_identity!(SharedFace, FaceKey);

impl<P: Payload> SharedFace<P> {
    fn from_view(map: SharedGMap<P>, view: Face<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<Face<'_, P>, ExploreError> {
        Face::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("face", self.dart.id()))
    }

    /// Returns the outer boundary loop.
    pub(crate) fn outer_loop(&self) -> Result<SharedLoop<P>, ExploreError> {
        Ok(SharedLoop::from_view(
            self.map.clone(),
            self.view()?.outer_loop(),
        ))
    }

    /// Returns inner boundary loops.
    pub(crate) fn inner_loops(&self) -> Result<Vec<SharedLoop<P>>, ExploreError> {
        Ok(self
            .view()?
            .inner_loops()
            .into_iter()
            .map(|view| SharedLoop::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns all boundary loops, outer first.
    pub(crate) fn loops(&self) -> Result<Vec<SharedLoop<P>>, ExploreError> {
        Ok(self
            .view()?
            .loops()
            .into_iter()
            .map(|view| SharedLoop::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns boundary edges in loop order.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns boundary vertices in loop order.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns a clone of the support surface.
    pub(crate) fn surface(&self) -> Result<Surface, ExploreError> {
        Ok(self.view()?.surface().clone())
    }

    /// Returns the pcurve assigned to a boundary dart, if present.
    pub(crate) fn pcurve(&self, dart: usize) -> Result<Option<Curve2>, ExploreError> {
        let dart = self.map.checked_dart(dart)?;
        Ok(self.view()?.pcurve(dart))
    }

    /// Returns the same face in the opposite orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.map.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only sheet handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedSheet<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: SheetKey,
    dart: Dart,
}

shared_identity!(SharedSheet, SheetKey);

impl<P: Payload> SharedSheet<P> {
    fn from_view(map: SharedGMap<P>, view: Sheet<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart,
        }
    }

    fn view(&self) -> Result<Sheet<'_, P>, ExploreError> {
        Sheet::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("sheet", self.dart.id()))
    }

    /// Returns all dart ids in this sheet.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns whether this sheet is closed.
    pub(crate) fn is_closed(&self) -> Result<bool, ExploreError> {
        Ok(self.view()?.is_closed())
    }

    /// Returns faces belonging to this sheet.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns unique edges belonging to this sheet.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns unique vertices belonging to this sheet.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns the same sheet in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.map.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only closed sheet handle.
#[derive(Clone)]
pub(crate) struct SharedShell<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: SheetKey,
    dart: Dart,
}

shared_identity!(SharedShell, SheetKey);

impl<P: Payload> SharedShell<P> {
    fn from_view(map: SharedGMap<P>, view: ShellRef<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart,
        }
    }

    fn view(&self) -> Result<ShellRef<'_, P>, ExploreError> {
        let sheet = Sheet::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("shell", self.dart.id()))?;
        Ok(Closed::new_unchecked(sheet))
    }

    /// Returns faces belonging to this shell.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns unique edges belonging to this shell.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns unique vertices belonging to this shell.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns the same shell in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.map.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only solid handle.
#[derive(Clone)]
pub(crate) struct SharedSolid<P: Payload = StandardPayload> {
    map: SharedGMap<P>,
    key: SolidKey,
    dart: Dart,
}

shared_identity!(SharedSolid, SolidKey);

impl<P: Payload> SharedSolid<P> {
    fn from_view(map: SharedGMap<P>, view: Solid<'_, P>) -> Self {
        Self {
            map,
            key: view.key(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<Solid<'_, P>, ExploreError> {
        Solid::from_dart(self.map.map(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("solid", self.dart.id()))
    }

    /// Returns the outer shell.
    pub(crate) fn outer_shell(&self) -> Result<SharedShell<P>, ExploreError> {
        Ok(SharedShell::from_view(
            self.map.clone(),
            self.view()?.outer_shell(),
        ))
    }

    /// Returns inner shells, with absent storage represented as an empty list.
    pub(crate) fn inner_shells(&self) -> Result<Vec<SharedShell<P>>, ExploreError> {
        Ok(self
            .view()?
            .inner_shells()
            .unwrap_or_default()
            .into_iter()
            .map(|view| SharedShell::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns all shells, outer first.
    pub(crate) fn shells(&self) -> Result<Vec<SharedShell<P>>, ExploreError> {
        Ok(self
            .view()?
            .shells()
            .into_iter()
            .map(|view| SharedShell::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns unique faces belonging to this solid.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns unique edges belonging to this solid.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.map.clone(), view))
            .collect())
    }

    /// Returns unique vertices belonging to this solid.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.map.clone(), view))
            .collect())
    }
}
