use std::sync::Arc;

use thiserror::Error;

use crate::geometry::{Curve, Point3, Surface, TrimmedCurve2};
use crate::model::{Cell1, MergeTopology, Model};
use crate::topology::closed::{Closeable, Closed};
use crate::topology::edge::{BoundedEdge, Edge};
use crate::topology::face::{Face, Loop};
#[cfg(feature = "python")]
use crate::model::Cell2;
#[cfg(feature = "python")]
use crate::topology::shape::FaceTag;
use crate::topology::gmap::{Dart, Dim, GMAP_INVOLUTION_COUNT};
use crate::topology::payload::{Payload, StandardPayload};
use crate::topology::profile::Profile;
use crate::topology::shape::{EdgeTag, ProfileTag, Shape};
use crate::topology::shape_keys::{EdgeKey, FaceKey, ProfileKey, SheetKey, SolidKey, VertexKey};
use crate::topology::sheet::{Sheet, ShellRef};
use crate::topology::solid::Solid;
use crate::topology::vertex::Vertex;

/// Errors returned by the language-neutral exploration API.
#[derive(Debug, Error)]
pub(crate) enum ExploreError {
    /// A dimension or involution index was outside the supported range.
    #[error("invalid dimension {dimension}; expected a value from 0 through {max}")]
    InvalidDimension { dimension: usize, max: usize },
    /// A dart id did not address a dart in the map.
    #[error("invalid dart {dart}; map contains {dart_count} darts")]
    InvalidDart { dart: usize, dart_count: usize },
    /// Incidence requires two different cell dimensions.
    #[error("incident cells require different dimensions, got {dimension} twice")]
    SameDimension { dimension: usize },
    /// A stored handle could no longer be resolved in its immutable map.
    #[error("missing {kind} for {locator}")]
    MissingEntity { kind: &'static str, locator: String },
    /// Serde could not encode or decode the complete map.
    #[error("failed to serialize or deserialize model: {0}")]
    Serde(#[from] serde_json::Error),
}

/// Immutable shared ownership of a model used by language binding objects.
pub(crate) struct SharedModel<P: Payload = StandardPayload> {
    model: Arc<Model<P>>,
}

impl<P: Payload> Clone for SharedModel<P> {
    fn clone(&self) -> Self {
        Self {
            model: Arc::clone(&self.model),
        }
    }
}

impl<P: Payload> SharedModel<P> {
    /// Wraps an owned model in immutable shared ownership.
    pub(crate) fn from_model(model: Model<P>) -> Self {
        Self {
            model: Arc::new(model),
        }
    }

    /// Returns the underlying read-only model.
    pub(crate) fn model(&self) -> &Model<P> {
        self.model.as_ref()
    }

    /// Returns an identity token unique to this in-memory map instance.
    #[cfg(feature = "python")]
    pub(crate) fn identity(&self) -> usize {
        Arc::as_ptr(&self.model) as usize
    }

    /// Returns whether both wrappers share the exact same map instance.
    pub(crate) fn ptr_eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.model, &other.model)
    }

    /// Returns the highest supported cell dimension.
    pub(crate) fn dimension(&self) -> usize {
        GMAP_INVOLUTION_COUNT - 1
    }

    /// Returns the number of alpha involutions.
    pub(crate) fn involution_count(&self) -> usize {
        GMAP_INVOLUTION_COUNT
    }

    /// Returns the number of addressable darts.
    pub(crate) fn dart_count(&self) -> usize {
        self.model.dart_count()
    }

    /// Returns all dart ids.
    pub(crate) fn darts(&self) -> Vec<usize> {
        self.model.darts().map(|dart| dart.id()).collect()
    }

    /// Evaluates one alpha involution with checked binding inputs.
    pub(crate) fn alpha(&self, dimension: usize, dart: usize) -> Result<usize, ExploreError> {
        let dimension = self.checked_dimension(dimension)?;
        let dart = self.checked_dart(dart)?;
        Ok(self.model.alpha(dimension, dart).id())
    }

    /// Reports whether a dart is free on one alpha involution.
    pub(crate) fn is_free(&self, dimension: usize, dart: usize) -> Result<bool, ExploreError> {
        let dimension = self.checked_dimension(dimension)?;
        let dart = self.checked_dart(dart)?;
        Ok(self.model.is_free(dart, dimension))
    }

    /// Returns the orbit generated by the requested alpha involutions.
    pub(crate) fn orbit(
        &self,
        dart: usize,
        involutions: Vec<usize>,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        for &involution in &involutions {
            self.checked_dimension(involution)?;
        }
        Ok(self
            .model
            .orbit(dart, involutions)
            .map(|dart| dart.id())
            .collect())
    }

    /// Returns one representative dart for every cell of a dimension.
    pub(crate) fn cells(&self, dimension: usize) -> Result<Vec<usize>, ExploreError> {
        let dimension = self.checked_dimension(dimension)?;
        Ok(self
            .model
            .cells(dimension)
            .map(|dart| self.model.cell_representative(dart, dimension).id())
            .collect())
    }

    /// Returns every dart in the requested cell.
    pub(crate) fn cell_darts(
        &self,
        dart: usize,
        dimension: usize,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let dimension = self.checked_dimension(dimension)?;
        Ok(self
            .model
            .orbit(dart, self.model.orbit_indices(dimension))
            .map(|dart| dart.id())
            .collect())
    }

    /// Returns the canonical representative dart of a cell.
    pub(crate) fn cell_representative(
        &self,
        dart: usize,
        dimension: usize,
    ) -> Result<usize, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let dimension = self.checked_dimension(dimension)?;
        Ok(self.model.cell_representative(dart, dimension).id())
    }

    /// Returns canonical representatives of cells incident to a container cell.
    pub(crate) fn incident_cells(
        &self,
        dart: usize,
        container_dimension: usize,
        target_dimension: usize,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let container = self.checked_dimension(container_dimension)?;
        let target = self.checked_dimension(target_dimension)?;
        if container == target {
            return Err(ExploreError::SameDimension {
                dimension: container_dimension,
            });
        }
        Ok(self
            .model
            .incident_cells(dart, container, target)
            .map(|dart| self.model.cell_representative(dart, target).id())
            .collect())
    }

    /// Returns canonical representatives of adjacent cells of a dimension.
    pub(crate) fn adjacent_cells(
        &self,
        dart: usize,
        dimension: usize,
    ) -> Result<Vec<usize>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        let dimension = self.checked_dimension(dimension)?;
        Ok(self
            .model
            .adjacent_cells(dart, dimension)
            .map(|dart| self.model.cell_representative(dart, dimension).id())
            .collect())
    }

    /// Returns every registered vertex in default orientation.
    pub(crate) fn vertices(&self) -> Vec<SharedVertex<P>> {
        self.model
            .iter_vertices()
            .map(|(key, _)| SharedVertex::from_view(self.clone(), self.model.vertex_unchecked(key)))
            .collect()
    }

    /// Returns every registered edge in default orientation.
    pub(crate) fn edges(&self) -> Vec<SharedEdge<P>> {
        self.model
            .iter_edges()
            .map(|(key, _)| SharedEdge::from_view(self.clone(), self.model.edge_unchecked(key)))
            .collect()
    }

    /// Returns every registered profile in default orientation.
    pub(crate) fn profiles(&self) -> Vec<SharedProfile<P>> {
        self.model
            .iter_profiles()
            .map(|(key, _)| {
                SharedProfile::from_view(self.clone(), self.model.profile_unchecked(key))
            })
            .collect()
    }

    /// Returns every registered face in default orientation.
    pub(crate) fn faces(&self) -> Vec<SharedFace<P>> {
        self.model
            .iter_faces()
            .map(|(key, _)| SharedFace::from_view(self.clone(), self.model.face_unchecked(key)))
            .collect()
    }

    /// Returns every registered sheet in default orientation.
    pub(crate) fn sheets(&self) -> Vec<SharedSheet<P>> {
        self.model
            .iter_sheets()
            .map(|(key, _)| SharedSheet::from_view(self.clone(), self.model.sheet_unchecked(key)))
            .collect()
    }

    /// Returns every registered solid in default orientation.
    pub(crate) fn solids(&self) -> Vec<SharedSolid<P>> {
        self.model
            .iter_solids()
            .map(|(key, _)| SharedSolid::from_view(self.clone(), self.model.solid_unchecked(key)))
            .collect()
    }

    /// Resolves the registered vertex containing a dart.
    pub(crate) fn vertex_at(&self, dart: usize) -> Result<Option<SharedVertex<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Vertex::from_dart(self.model(), dart)
            .map(|view| SharedVertex::from_view(self.clone(), view)))
    }

    /// Resolves the registered edge containing a dart.
    pub(crate) fn edge_at(&self, dart: usize) -> Result<Option<SharedEdge<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Edge::from_dart(self.model(), dart)
            .map(|view| SharedEdge::from_view(self.clone(), view)))
    }

    /// Resolves the registered profile containing a dart.
    pub(crate) fn profile_at(&self, dart: usize) -> Result<Option<SharedProfile<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Profile::from_dart(self.model(), dart)
            .map(|view| SharedProfile::from_view(self.clone(), view)))
    }

    /// Resolves the registered face containing a dart.
    pub(crate) fn face_at(&self, dart: usize) -> Result<Option<SharedFace<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Face::from_dart(self.model(), dart)
            .map(|view| SharedFace::from_view(self.clone(), view)))
    }

    /// Resolves the registered sheet containing a dart.
    pub(crate) fn sheet_at(&self, dart: usize) -> Result<Option<SharedSheet<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Sheet::from_dart(self.model(), dart)
            .map(|view| SharedSheet::from_view(self.clone(), view)))
    }

    /// Resolves the registered solid containing a dart.
    pub(crate) fn solid_at(&self, dart: usize) -> Result<Option<SharedSolid<P>>, ExploreError> {
        let dart = self.checked_dart(dart)?;
        Ok(Solid::from_dart(self.model(), dart)
            .map(|view| SharedSolid::from_view(self.clone(), view)))
    }

    /// Resolves a registered edge from its stable key.
    pub(crate) fn edge_by_key(&self, key: EdgeKey) -> Option<SharedEdge<P>> {
        self.model
            .edge(key)
            .map(|view| SharedEdge::from_view(self.clone(), view))
    }

    /// Resolves a registered profile from its stable key.
    pub(crate) fn profile_by_key(&self, key: ProfileKey) -> Option<SharedProfile<P>> {
        self.model
            .profile(key)
            .map(|view| SharedProfile::from_view(self.clone(), view))
    }

    /// Resolves a registered face from its stable key.
    pub(crate) fn face_by_key(&self, key: FaceKey) -> Option<SharedFace<P>> {
        self.model
            .face(key)
            .map(|view| SharedFace::from_view(self.clone(), view))
    }

    /// Resolves a registered solid from its stable key.
    pub(crate) fn solid_by_key(&self, key: SolidKey) -> Option<SharedSolid<P>> {
        self.model
            .solid(key)
            .map(|view| SharedSolid::from_view(self.clone(), view))
    }

    fn checked_dimension(&self, dimension: usize) -> Result<Dim, ExploreError> {
        if dimension >= GMAP_INVOLUTION_COUNT {
            return Err(ExploreError::InvalidDimension {
                dimension,
                max: GMAP_INVOLUTION_COUNT - 1,
            });
        }
        Ok(Dim::from_index(dimension))
    }

    fn checked_dart(&self, dart: usize) -> Result<Dart, ExploreError> {
        if dart >= self.model.dart_count() {
            return Err(ExploreError::InvalidDart {
                dart,
                dart_count: self.model.dart_count(),
            });
        }
        Ok(Dart::new(dart))
    }
}

impl SharedModel<StandardPayload> {
    /// Serializes the complete immutable map as JSON.
    pub(crate) fn serialize(&self) -> Result<String, ExploreError> {
        Ok(serde_json::to_string(self.model())?)
    }

    /// Deserializes a complete standard-payload map without validation.
    pub(crate) fn deserialize(serialized: &str) -> Result<Self, ExploreError> {
        let map = serde_json::from_str(serialized)?;
        Ok(Self::from_model(map))
    }
}

fn missing(kind: &'static str, locator: impl ToString) -> ExploreError {
    ExploreError::MissingEntity {
        kind,
        locator: locator.to_string(),
    }
}

macro_rules! shared_identity {
    ($type:ident, $key:ty) => {
        impl<P: Payload> $type<P> {
            /// Returns this handle's shared map.
            pub(crate) fn model(&self) -> SharedModel<P> {
                self.model.clone()
            }

            /// Returns its opaque stable key.
            pub(crate) fn key(&self) -> $key {
                self.key
            }

            /// Returns its contextual dart id when this entity is dart-backed.
            pub(crate) fn dart_id(&self) -> Option<usize> {
                self.contextual_dart_id()
            }

            /// Returns whether both handles identify the same entity in the same map.
            pub(crate) fn same_entity(&self, other: &Self) -> bool {
                self.model.ptr_eq(&other.model) && self.key == other.key
            }
        }

        impl<P: Payload> PartialEq for $type<P> {
            fn eq(&self, other: &Self) -> bool {
                self.same_entity(other)
            }
        }

        impl<P: Payload> Eq for $type<P> {}
    };
}

/// Owned read-only vertex handle.
#[derive(Clone)]
pub(crate) struct SharedVertex<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: VertexKey,
    dart: Dart,
}

shared_identity!(SharedVertex, VertexKey);

impl<P: Payload> SharedVertex<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: Vertex<'_, P>) -> Self {
        Self {
            model,
            key: view.key(),
            dart: view.dart,
        }
    }

    fn view(&self) -> Result<Vertex<'_, P>, ExploreError> {
        Vertex::from_dart(self.model.model(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("vertex", self.dart.id()))
    }

    /// Returns the stored point geometry.
    pub(crate) fn point(&self) -> Result<Option<Point3>, ExploreError> {
        Ok(self.view()?.point().copied())
    }

    /// Returns incident edges.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns incident faces.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns incident sheets.
    pub(crate) fn sheets(&self) -> Result<Vec<SharedSheet<P>>, ExploreError> {
        Ok(self
            .view()?
            .sheets()
            .into_iter()
            .map(|view| SharedSheet::from_view(self.model.clone(), view))
            .collect())
    }
}

/// Owned read-only edge handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedEdge<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: EdgeKey,
    dart: Dart,
}

shared_identity!(SharedEdge, EdgeKey);

impl<P: Payload> SharedEdge<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: Edge<'_, P>) -> Self {
        Self {
            model,
            key: view.key(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<Edge<'_, P>, ExploreError> {
        Edge::from_dart(self.model.model(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("edge", self.dart.id()))
    }

    /// Returns all darts in this edge cell.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns the oriented start vertex.
    ///
    /// Errors on a closed edge, which has no end to name â€” ask `vertices()`
    /// instead for the one vertex it passes through.
    pub(crate) fn start(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.model.clone(),
            self.bounded()?.start(),
        ))
    }

    /// Returns the oriented end vertex.
    ///
    /// Errors on a closed edge, for the same reason as [`Self::start`].
    pub(crate) fn end(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.model.clone(),
            self.bounded()?.end(),
        ))
    }

    /// Resolves this edge as a bounded one, erroring when it closes on itself.
    fn bounded(&self) -> Result<BoundedEdge<'_, P>, ExploreError> {
        self.view()?
            .bounded()
            .ok_or_else(|| missing("bounded edge", self.dart.id()))
    }

    /// Returns distinct incident vertices.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns incident faces.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns incident sheets.
    pub(crate) fn sheets(&self) -> Result<Vec<SharedSheet<P>>, ExploreError> {
        Ok(self
            .view()?
            .sheets()
            .into_iter()
            .map(|view| SharedSheet::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns a clone of the attached curve.
    pub(crate) fn curve(&self) -> Result<Option<Curve>, ExploreError> {
        Ok(self.view()?.curve().cloned())
    }

    /// Returns the geometric edge length when geometry is available.
    pub(crate) fn length(&self) -> Result<Option<f64>, ExploreError> {
        Ok(self.view()?.length())
    }

    /// Returns the same edge in the opposite orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.model.clone(), self.view()?.reversed()))
    }

    /// Copies this edge into an owned shape for a modeling constructor.
    pub(crate) fn isolated_shape(&self) -> Result<Shape<EdgeTag, P>, ExploreError> {
        let (model, dart) = self.view()?.isolate();
        let key = model.cell_key_unchecked::<Cell1>(dart);
        Ok(Shape::new(model, key))
    }
}

/// Owned read-only profile handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedProfile<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: ProfileKey,
    dart: Dart,
}

shared_identity!(SharedProfile, ProfileKey);

impl<P: Payload> SharedProfile<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: Profile<'_, P>) -> Self {
        Self {
            model,
            key: view.key(),
            dart: view.dart,
        }
    }

    fn view(&self) -> Result<Profile<'_, P>, ExploreError> {
        Profile::from_dart(self.model.model(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("profile", self.dart.id()))
    }

    /// Returns traversal-order dart ids.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns whether this profile is closed.
    pub(crate) fn is_closed(&self) -> Result<bool, ExploreError> {
        Ok(self.view()?.is_closed())
    }

    /// Returns the first traversal vertex.
    pub(crate) fn start(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.model.clone(),
            self.view()?.start(),
        ))
    }

    /// Returns the final traversal vertex.
    pub(crate) fn end(&self) -> Result<SharedVertex<P>, ExploreError> {
        Ok(SharedVertex::from_view(
            self.model.clone(),
            self.view()?.end(),
        ))
    }

    /// Returns traversal-order edges.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns traversal-order vertices.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns the same profile in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.model.clone(), self.view()?.reversed()))
    }

    /// Copies this profile into an owned shape for a modeling constructor.
    pub(crate) fn isolated_shape(&self) -> Result<Shape<ProfileTag, P>, ExploreError> {
        let (model, dart) = self.view()?.isolate();
        let key = Profile::from_dart(&model, dart)
            .ok_or_else(|| missing("profile", dart.id()))?
            .key();
        Ok(Shape::new(model, key))
    }
}

/// Owned read-only closed profile handle.
#[derive(Clone)]
pub(crate) struct SharedLoop<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: ProfileKey,
    dart: Dart,
}

shared_identity!(SharedLoop, ProfileKey);

impl<P: Payload> SharedLoop<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: Loop<'_, P>) -> Self {
        Self {
            model,
            key: view.profile_key().unwrap_or_default(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<Loop<'_, P>, ExploreError> {
        let face = Face::from_dart(self.model.model(), self.dart)
            .ok_or_else(|| missing("loop face", self.dart.id()))?;
        face.loops()
            .into_iter()
            .find(|loop_| loop_.dart() == self.dart)
            .ok_or_else(|| missing("loop", self.dart.id()))
    }

    /// Returns traversal-order dart ids.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns traversal-order edges.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns traversal-order vertices.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns the same loop in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.model.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only face handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedFace<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: FaceKey,
    dart: Dart,
}

shared_identity!(SharedFace, FaceKey);

impl<P: Payload> SharedFace<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: Face<'_, P>) -> Self {
        Self {
            model,
            key: view.key(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<Face<'_, P>, ExploreError> {
        Face::from_dart(self.model.model(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("face", format!("{:?}", self.key)))
    }

    /// Returns the outer boundary loop.
    ///
    /// A ring face â€” a cylinder wall â€” is bounded by wrapping loops and has
    /// none; read its whole boundary with [`Self::loops`] instead.
    pub(crate) fn outer_loop(&self) -> Result<SharedLoop<P>, ExploreError> {
        let outer = self
            .view()?
            .outer_loop()
            .ok_or_else(|| missing("outer loop", format!("{:?}", self.key)))?;
        Ok(SharedLoop::from_view(self.model.clone(), outer))
    }

    /// Returns inner boundary loops.
    pub(crate) fn inner_loops(&self) -> Result<Vec<SharedLoop<P>>, ExploreError> {
        Ok(self
            .view()?
            .inner_loops()
            .into_iter()
            .map(|view| SharedLoop::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns all boundary loops, outer first.
    pub(crate) fn loops(&self) -> Result<Vec<SharedLoop<P>>, ExploreError> {
        Ok(self
            .view()?
            .loops()
            .into_iter()
            .map(|view| SharedLoop::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns boundary edges in loop order.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns boundary vertices in loop order.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns a clone of the support surface.
    pub(crate) fn surface(&self) -> Result<Surface, ExploreError> {
        Ok(self.view()?.surface().clone())
    }

    /// Returns the pcurve assigned to a boundary dart, if present.
    pub(crate) fn pcurve(&self, dart: usize) -> Result<Option<TrimmedCurve2>, ExploreError> {
        let dart = self.model.checked_dart(dart)?;
        Ok(self.view()?.pcurve(dart))
    }

    /// Returns the same face in the opposite orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.model.clone(), self.view()?.reversed()))
    }

    /// Copies this face into an owned shape for a modeling constructor.
    #[cfg(feature = "python")]
    pub(crate) fn isolated_shape(&self) -> Result<Shape<FaceTag, P>, ExploreError> {
        let (model, dart) = self.view()?.isolate();
        let key = model.cell_key_unchecked::<Cell2>(dart);
        Ok(Shape::new(model, key))
    }
}

/// Owned read-only sheet handle preserving traversal orientation.
#[derive(Clone)]
pub(crate) struct SharedSheet<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: SheetKey,
    dart: Dart,
}

shared_identity!(SharedSheet, SheetKey);

impl<P: Payload> SharedSheet<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: Sheet<'_, P>) -> Self {
        Self {
            model,
            key: view.key(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<Sheet<'_, P>, ExploreError> {
        Sheet::from_dart(self.model.model(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("sheet", format!("{:?}", self.key)))
    }

    /// Returns all dart ids in this sheet.
    pub(crate) fn darts(&self) -> Result<Vec<usize>, ExploreError> {
        Ok(self.view()?.darts().map(|dart| dart.id()).collect())
    }

    /// Returns whether this sheet is closed.
    pub(crate) fn is_closed(&self) -> Result<bool, ExploreError> {
        Ok(self.view()?.is_closed())
    }

    /// Returns faces belonging to this sheet.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns unique edges belonging to this sheet.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns unique vertices belonging to this sheet.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns the same sheet in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.model.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only closed sheet handle.
#[derive(Clone)]
pub(crate) struct SharedShell<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: SheetKey,
    dart: Dart,
}

shared_identity!(SharedShell, SheetKey);

impl<P: Payload> SharedShell<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: ShellRef<'_, P>) -> Self {
        Self {
            model,
            key: view.key(),
            dart: view.dart(),
        }
    }

    fn view(&self) -> Result<ShellRef<'_, P>, ExploreError> {
        let sheet = Sheet::from_dart(self.model.model(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("shell", format!("{:?}", self.key)))?;
        Ok(Closed::new_unchecked(sheet))
    }

    /// Returns faces belonging to this shell.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns unique edges belonging to this shell.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns unique vertices belonging to this shell.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns the same shell in the opposite traversal orientation.
    pub(crate) fn reversed(&self) -> Result<Self, ExploreError> {
        Ok(Self::from_view(self.model.clone(), self.view()?.reversed()))
    }
}

/// Owned read-only solid handle.
#[derive(Clone)]
pub(crate) struct SharedSolid<P: Payload = StandardPayload> {
    model: SharedModel<P>,
    key: SolidKey,
    dart: Dart,
}

shared_identity!(SharedSolid, SolidKey);

impl<P: Payload> SharedSolid<P> {
    fn contextual_dart_id(&self) -> Option<usize> {
        Some(self.dart.id())
    }

    fn from_view(model: SharedModel<P>, view: Solid<'_, P>) -> Self {
        Self {
            model,
            key: view.key(),
            dart: view.dart(),
        }
    }

    pub(crate) fn view(&self) -> Result<Solid<'_, P>, ExploreError> {
        Solid::from_dart(self.model.model(), self.dart)
            .filter(|view| view.key() == self.key)
            .ok_or_else(|| missing("solid", format!("{:?}", self.key)))
    }

    /// Returns the outer shell.
    pub(crate) fn outer_shell(&self) -> Result<SharedShell<P>, ExploreError> {
        Ok(SharedShell::from_view(
            self.model.clone(),
            self.view()?.outer_shell(),
        ))
    }

    /// Returns inner shells, with absent storage represented as an empty list.
    pub(crate) fn inner_shells(&self) -> Result<Vec<SharedShell<P>>, ExploreError> {
        Ok(self
            .view()?
            .inner_shells()
            .unwrap_or_default()
            .into_iter()
            .map(|view| SharedShell::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns all shells, outer first.
    pub(crate) fn shells(&self) -> Result<Vec<SharedShell<P>>, ExploreError> {
        Ok(self
            .view()?
            .shells()
            .into_iter()
            .map(|view| SharedShell::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns unique faces belonging to this solid.
    pub(crate) fn faces(&self) -> Result<Vec<SharedFace<P>>, ExploreError> {
        Ok(self
            .view()?
            .faces()
            .into_iter()
            .map(|view| SharedFace::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns unique edges belonging to this solid.
    pub(crate) fn edges(&self) -> Result<Vec<SharedEdge<P>>, ExploreError> {
        Ok(self
            .view()?
            .edges()
            .into_iter()
            .map(|view| SharedEdge::from_view(self.model.clone(), view))
            .collect())
    }

    /// Returns unique vertices belonging to this solid.
    pub(crate) fn vertices(&self) -> Result<Vec<SharedVertex<P>>, ExploreError> {
        Ok(self
            .view()?
            .vertices()
            .into_iter()
            .map(|view| SharedVertex::from_view(self.model.clone(), view))
            .collect())
    }
}
