from ..topology import Edge, Face, Profile, Solid, Vertex


class BlendTarget:
    def add_vertex(self, vertex: Vertex) -> None: ...
    def add_edge(self, edge: Edge) -> None: ...
    def add_profile(self, profile: Profile) -> None: ...
    def add_face(self, face: Face) -> None: ...


def filleted_profile(shape: Profile, target: BlendTarget, radius: float) -> Profile: ...
def filleted_face(shape: Face, target: BlendTarget, radius: float) -> Face: ...
def filleted_solid(shape: Solid, target: BlendTarget, radius: float) -> Solid: ...
def chamfered_profile(shape: Profile, target: BlendTarget, distance: float) -> Profile: ...
def chamfered_face(shape: Face, target: BlendTarget, distance: float) -> Face: ...
def chamfered_solid(shape: Solid, target: BlendTarget, distance: float) -> Solid: ...
