from ..topology import Face, Model, Solid

class FaceBooleanResult:
    @property
    def model(self) -> Model: ...
    def faces(self) -> list[Face]: ...

def fuse(first: Solid, second: Solid) -> Solid: ...
def cut(target: Solid, tool: Solid) -> Solid: ...
def intersect(first: Solid, second: Solid) -> Solid: ...
def fuse_faces(first: Face, second: Face) -> FaceBooleanResult: ...
def cut_faces(first: Face, second: Face) -> FaceBooleanResult: ...
def intersect_faces(first: Face, second: Face) -> FaceBooleanResult: ...
