from ..geometry import Axis, Plane
from ..topology import Edge, Face, Model, Vertex

class EdgeSplitResult:
    @property
    def model(self) -> Model: ...
    @property
    def separated(self) -> bool: ...
    def edges(self) -> list[Edge]: ...
    def vertex(self) -> Vertex: ...
    def face(self) -> Face | None: ...

def line(start: tuple[float, float, float], end: tuple[float, float, float]) -> Edge: ...
def arc(plane: Plane, radius: float, start_angle: float, end_angle: float) -> Edge: ...
def helix(axis: Axis, radius: float, pitch: float, start_angle: float, end_angle: float) -> Edge: ...
def circle(plane: Plane, radius: float) -> Edge: ...
def split(edge: Edge, fraction: float) -> EdgeSplitResult: ...
