from ..geometry import Plane
from ..topology import Face, Profile

def rectangle(x_size: float, y_size: float) -> Face: ...
def polygon(points: list[tuple[float, float, float]]) -> Face: ...
def circle(plane: Plane, radius: float) -> Face: ...
def annulus(plane: Plane, outer_radius: float, inner_radius: float) -> Face: ...
def from_profile(profile: Profile) -> Face: ...
