from ..geometry import Plane
from ..topology import Edge, Face, Profile
from .edges import EdgeSplitResult

def rectangle(x_size: float, y_size: float, plane: Plane | None = None) -> Face: ...
def square(size: float, plane: Plane | None = None) -> Face: ...
def polygon(points: list[tuple[float, float, float]]) -> Face: ...
def polygon_with_holes(
    outer: list[tuple[float, float, float]],
    holes: list[list[tuple[float, float, float]]],
    plane: Plane | None = None,
) -> Face: ...
def circle(radius: float, plane: Plane | None = None) -> Face: ...
def annulus(outer_radius: float, inner_radius: float, plane: Plane | None = None) -> Face: ...
def from_profile(profile: Profile) -> Face: ...
def split_boundary_edge(face: Face, edge: Edge, fraction: float) -> EdgeSplitResult: ...
