from ..geometry import Plane
from ..topology import Face, Profile

def rectangle(x_size: float, y_size: float, plane: Plane | None = None) -> Face: ...
def polygon(points: list[tuple[float, float, float]]) -> Face: ...
def circle(radius: float, plane: Plane | None = None) -> Face: ...
def annulus(outer_radius: float, inner_radius: float, plane: Plane | None = None) -> Face: ...
def from_profile(profile: Profile) -> Face: ...
