from .. import Edge, Profile

def rectangle(x_size: float, y_size: float) -> Profile: ...
def polygon(points: list[tuple[float, float, float]]) -> Profile: ...
def from_edges(edges: list[Edge]) -> Profile: ...
