from ..geometry import Plane
from ..topology import Edge, Profile

def rectangle(x_size: float, y_size: float, plane: Plane | None = None) -> Profile: ...
def square(size: float, plane: Plane | None = None) -> Profile: ...
def polyline(points: list[tuple[float, float, float]]) -> Profile: ...
def polygon(points: list[tuple[float, float, float]]) -> Profile: ...
def arc(plane: Plane, radius: float, start_angle: float, end_angle: float) -> Profile: ...
def from_edges(edges: list[Edge]) -> Profile: ...
def from_edge(edge: Edge) -> Profile: ...
def appended(profile: Profile, edge: Edge) -> Profile: ...
