from ..geometry import Plane
from ..topology import Edge, Profile

def rectangle(x_size: float, y_size: float, plane: Plane | None = None) -> Profile: ...
def polygon(points: list[tuple[float, float, float]]) -> Profile: ...
def from_edges(edges: list[Edge]) -> Profile: ...
