from .. import Face, Frame, Solid, Vector

def block(x: float, y: float, z: float, frame: Frame | None = None) -> Solid: ...
def cylinder(radius: float, height: float, frame: Frame | None = None) -> Solid: ...
def sphere(radius: float, frame: Frame | None = None) -> Solid: ...
def torus(major: float, minor: float, frame: Frame | None = None) -> Solid: ...
def extruded(face: Face, direction: Vector, distance: float) -> Solid: ...
def fuse(first: Solid, second: Solid) -> Solid: ...
def cut(target: Solid, tool: Solid) -> Solid: ...
def intersect(first: Solid, second: Solid) -> Solid: ...
