from ..geometry import Frame, Vector
from ..topology import Face, Solid

def block(x: float, y: float, z: float, frame: Frame | None = None) -> Solid: ...
def cylinder(radius: float, height: float, frame: Frame | None = None) -> Solid: ...
def sphere(radius: float, frame: Frame | None = None) -> Solid: ...
def torus(major: float, minor: float, frame: Frame | None = None) -> Solid: ...
def extruded(face: Face, direction: Vector, distance: float) -> Solid: ...
