from ..geometry import Rigid
from ..topology import Edge, Face, Profile, Sheet, Solid


def moved_edge(shape: Edge, motion: Rigid) -> Edge: ...
def moved_profile(shape: Profile, motion: Rigid) -> Profile: ...
def moved_face(shape: Face, motion: Rigid) -> Face: ...
def moved_sheet(shape: Sheet, motion: Rigid) -> Sheet: ...
def moved_solid(shape: Solid, motion: Rigid) -> Solid: ...
