use js_sys::Array;
use wasm_bindgen::prelude::*;

use super::common::{Map, js_err, values};
use super::{WasmEdge, WasmFace, WasmProfile, WasmSheet, WasmSolid, WasmVertex};

#[wasm_bindgen(js_name = GMap)]
#[derive(Clone)]
pub struct WasmGMap {
    pub(crate) inner: Map,
}

impl WasmGMap {
    pub(crate) fn from_inner(inner: Map) -> Self {
        Self { inner }
    }
}

#[wasm_bindgen]
impl WasmGMap {
    /// Deserializes a complete standard-payload GMap without validation.
    #[wasm_bindgen(js_name = deserialize)]
    pub fn deserialize(serialized: &str) -> Result<WasmGMap, JsValue> {
        Ok(Self::from_inner(
            Map::deserialize(serialized).map_err(js_err)?,
        ))
    }

    /// Serializes the complete map to JSON.
    pub fn serialize(&self) -> Result<String, JsValue> {
        self.inner.serialize().map_err(js_err)
    }

    /// Returns the highest cell dimension.
    #[wasm_bindgen(getter)]
    pub fn dimension(&self) -> usize {
        self.inner.dimension()
    }

    /// Returns the number of alpha involutions.
    #[wasm_bindgen(getter, js_name = involutionCount)]
    pub fn involution_count(&self) -> usize {
        self.inner.involution_count()
    }

    /// Returns the number of darts.
    #[wasm_bindgen(getter, js_name = dartCount)]
    pub fn dart_count(&self) -> usize {
        self.inner.dart_count()
    }

    /// Returns all dart ids.
    pub fn darts(&self) -> Vec<usize> {
        self.inner.darts()
    }

    /// Evaluates alpha_i(dart).
    pub fn alpha(&self, dimension: usize, dart: usize) -> Result<usize, JsValue> {
        self.inner.alpha(dimension, dart).map_err(js_err)
    }

    /// Reports whether a dart is free on an involution.
    #[wasm_bindgen(js_name = isFree)]
    pub fn is_free(&self, dimension: usize, dart: usize) -> Result<bool, JsValue> {
        self.inner.is_free(dimension, dart).map_err(js_err)
    }

    /// Returns an orbit generated by selected involutions.
    pub fn orbit(&self, dart: usize, involutions: Vec<usize>) -> Result<Vec<usize>, JsValue> {
        self.inner.orbit(dart, involutions).map_err(js_err)
    }

    /// Returns one representative dart for every cell of a dimension.
    pub fn cells(&self, dimension: usize) -> Result<Vec<usize>, JsValue> {
        self.inner.cells(dimension).map_err(js_err)
    }

    /// Returns all darts in one cell.
    #[wasm_bindgen(js_name = cellDarts)]
    pub fn cell_darts(&self, dart: usize, dimension: usize) -> Result<Vec<usize>, JsValue> {
        self.inner.cell_darts(dart, dimension).map_err(js_err)
    }

    /// Returns a cell's canonical representative dart.
    #[wasm_bindgen(js_name = cellRepresentative)]
    pub fn cell_representative(&self, dart: usize, dimension: usize) -> Result<usize, JsValue> {
        self.inner
            .cell_representative(dart, dimension)
            .map_err(js_err)
    }

    /// Returns representative darts for incident cells.
    #[wasm_bindgen(js_name = incidentCells)]
    pub fn incident_cells(
        &self,
        dart: usize,
        container_dimension: usize,
        target_dimension: usize,
    ) -> Result<Vec<usize>, JsValue> {
        self.inner
            .incident_cells(dart, container_dimension, target_dimension)
            .map_err(js_err)
    }

    /// Returns representative darts for adjacent cells.
    #[wasm_bindgen(js_name = adjacentCells)]
    pub fn adjacent_cells(&self, dart: usize, dimension: usize) -> Result<Vec<usize>, JsValue> {
        self.inner.adjacent_cells(dart, dimension).map_err(js_err)
    }

    /// Returns every registered vertex.
    #[wasm_bindgen(unchecked_return_type = "Vertex[]")]
    pub fn vertices(&self) -> Array {
        values(
            self.inner
                .vertices()
                .into_iter()
                .map(|inner| WasmVertex::from_inner(inner).into()),
        )
    }

    /// Returns every registered edge.
    #[wasm_bindgen(unchecked_return_type = "Edge[]")]
    pub fn edges(&self) -> Array {
        values(
            self.inner
                .edges()
                .into_iter()
                .map(|inner| WasmEdge::from_inner(inner).into()),
        )
    }

    /// Returns every registered profile.
    #[wasm_bindgen(unchecked_return_type = "Profile[]")]
    pub fn profiles(&self) -> Array {
        values(
            self.inner
                .profiles()
                .into_iter()
                .map(|inner| WasmProfile::from_inner(inner).into()),
        )
    }

    /// Returns every registered face.
    #[wasm_bindgen(unchecked_return_type = "Face[]")]
    pub fn faces(&self) -> Array {
        values(
            self.inner
                .faces()
                .into_iter()
                .map(|inner| WasmFace::from_inner(inner).into()),
        )
    }

    /// Returns every registered sheet.
    #[wasm_bindgen(unchecked_return_type = "Sheet[]")]
    pub fn sheets(&self) -> Array {
        values(
            self.inner
                .sheets()
                .into_iter()
                .map(|inner| WasmSheet::from_inner(inner).into()),
        )
    }

    /// Returns every registered solid.
    #[wasm_bindgen(unchecked_return_type = "Solid[]")]
    pub fn solids(&self) -> Array {
        values(
            self.inner
                .solids()
                .into_iter()
                .map(|inner| WasmSolid::from_inner(inner).into()),
        )
    }

    /// Resolves a registered vertex from a dart.
    pub fn vertex(&self, dart: usize) -> Result<Option<WasmVertex>, JsValue> {
        Ok(self
            .inner
            .vertex_at(dart)
            .map_err(js_err)?
            .map(WasmVertex::from_inner))
    }

    /// Resolves a registered edge from a dart.
    pub fn edge(&self, dart: usize) -> Result<Option<WasmEdge>, JsValue> {
        Ok(self
            .inner
            .edge_at(dart)
            .map_err(js_err)?
            .map(WasmEdge::from_inner))
    }

    /// Resolves a registered profile from a dart.
    pub fn profile(&self, dart: usize) -> Result<Option<WasmProfile>, JsValue> {
        Ok(self
            .inner
            .profile_at(dart)
            .map_err(js_err)?
            .map(WasmProfile::from_inner))
    }

    /// Resolves a registered face from a dart.
    pub fn face(&self, dart: usize) -> Result<Option<WasmFace>, JsValue> {
        Ok(self
            .inner
            .face_at(dart)
            .map_err(js_err)?
            .map(WasmFace::from_inner))
    }

    /// Resolves a registered sheet from a dart.
    pub fn sheet(&self, dart: usize) -> Result<Option<WasmSheet>, JsValue> {
        Ok(self
            .inner
            .sheet_at(dart)
            .map_err(js_err)?
            .map(WasmSheet::from_inner))
    }

    /// Resolves a registered solid from a dart.
    pub fn solid(&self, dart: usize) -> Result<Option<WasmSolid>, JsValue> {
        Ok(self
            .inner
            .solid_at(dart)
            .map_err(js_err)?
            .map(WasmSolid::from_inner))
    }

    /// Tests whether two wrappers own the same in-memory map.
    pub fn equals(&self, other: &WasmGMap) -> bool {
        self.inner.ptr_eq(&other.inner)
    }
}
