use std::collections::HashMap;

use nalgebra::{Rotation3, Vector3, distance};
use radians::{Angle, Rad64};
use thiserror::Error;

use crate::builders::faces::reverse_face_winding;
use crate::geometry::axis::Axis3;
use crate::geometry::nurbs::error::NurbsError;
use crate::geometry::{
    ANGULAR_TOLERANCE, Circle, Curve, Curve2, Interval, LINEAR_TOLERANCE, Line2, Plane, Point2,
    Point3, Surface, SurfaceOfRevolution,
};
use crate::topology::IsolatedDart;
use crate::topology::attributes::{
    EdgeAttr, FaceAttr, ProfileAttr, SheetAttr, SolidAttr, VertexAttr,
};
use crate::topology::closed::Closeable;
use crate::topology::edge::Edge;
use crate::topology::edit::{TopologyEdit, TopologyEditError};
use crate::topology::face::Face;
use crate::topology::gmap::{Cell2, Dart, Dim, GMap, MergeTopology};
use crate::topology::payload::Payload;
use crate::topology::planar::{Planar, PlanarityError};
use crate::topology::profile::Profile;
use crate::topology::shape::{FaceTag, Shape};
use crate::topology::shape_keys::{EdgeKey, FaceKey, ProfileKey, SheetKey, SolidKey, VertexKey};
use crate::topology::vertex::Vertex;

#[derive(Debug, Error)]
pub enum RevolveError {
    #[error("The provided profile is not planar")]
    PlanarError(PlanarityError),

    #[error("Missing edge for key {key:?}")]
    MissingEdge { key: EdgeKey },

    #[error("Missing vertex point for dart {dart:?}")]
    MissingVertexPoint { dart: Dart },

    #[error("Missing edge curve for dart {dart:?}")]
    MissingEdgeCurve { dart: Dart },

    #[error("Missing face for key {key:?}")]
    MissingFace { key: FaceKey },

    #[error("Edge {key:?} must be isolated before it can be consumed by a full revolution")]
    SourceEdgeNotIsolated { key: EdgeKey },

    #[error("A full revolution of closed edge {key:?} has no boundary loops")]
    BoundarylessFullRevolve { key: EdgeKey },

    #[error("Edge {key:?} lies on the revolution axis and sweeps no area")]
    EdgeOnRevolutionAxis { key: EdgeKey },

    #[error("Edge {key:?} touches the revolution axis; apex faces are not supported yet")]
    ApexRevolveUnsupported { key: EdgeKey },

    #[error("failed to rotate the geometry of dart {dart:?}")]
    RotationFailed { dart: Dart, source: NurbsError },

    #[error("Darts {first:?} and {second:?} are not sewable in dimension {dim:?}")]
    SewFailed { dim: Dim, first: Dart, second: Dart },

    #[error("failed to create revolved face topology")]
    TopologyEditFailed(#[from] TopologyEditError),
}

#[derive(Clone)]
struct RevolvedSourceVertex {
    key: VertexKey,
    point: Point3,
}

#[derive(Clone)]
struct RevolvedSourceEdge {
    key: EdgeKey,
    dart: Dart,
    start: RevolvedSourceVertex,
    end: RevolvedSourceVertex,
    curve: Curve,
}

impl RevolvedSourceVertex {
    fn from_vertex<P: Payload>(vertex: Vertex<'_, P>) -> Result<Self, RevolveError> {
        let point = *vertex
            .point()
            .ok_or(RevolveError::MissingVertexPoint { dart: vertex.dart })?;
        Ok(Self {
            key: vertex.key(),
            point,
        })
    }
}

impl RevolvedSourceEdge {
    fn from_key<P: Payload>(g: &GMap<P>, key: EdgeKey) -> Result<Self, RevolveError> {
        let edge = g.edge(key).ok_or(RevolveError::MissingEdge { key })?;
        Self::from_edge(edge)
    }

    fn from_edge<P: Payload>(edge: Edge<'_, P>) -> Result<Self, RevolveError> {
        let key = edge.key();
        let dart = edge.dart();
        let start = RevolvedSourceVertex::from_vertex(edge.start())?;
        let end = RevolvedSourceVertex::from_vertex(edge.end())?;
        let curve = edge
            .curve()
            .ok_or(RevolveError::MissingEdgeCurve { dart })?
            .clone();

        Ok(Self {
            key,
            dart,
            start,
            end,
            curve,
        })
    }
}

/// Adds a face generated by revolving `edge` around `axis`.
///
/// Angles are clamped to the inclusive range from zero to one full turn. A
/// partial turn reuses the source edge and its vertices as one face boundary.
/// A full turn consumes the isolated source topology and creates only the
/// non-degenerate circular loops swept by endpoints away from the axis.
/// Closed source edges cannot currently be fully revolved because the result
/// has no boundary loop that can seed a face.
pub fn add_revolved_edge<P: Payload>(
    g: &mut GMap<P>,
    edge: EdgeKey,
    axis: Axis3,
    angle: Rad64,
) -> Result<FaceKey, RevolveError> {
    g.transaction(|g| add_revolved_edge_staged(g, edge, axis, angle))
}

/// Revolves an edge inside the caller's active transaction.
pub(crate) fn add_revolved_edge_staged<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    edge: EdgeKey,
    axis: Axis3,
    angle: Rad64,
) -> Result<FaceKey, RevolveError> {
    let source = RevolvedSourceEdge::from_key(g, edge)?;
    let angle = angle.clamp(Angle::ZERO, Angle::FULL_TURN);
    if is_full_turn(angle) {
        return add_full_revolved_edge_face(g, &source, axis, angle);
    }

    add_partial_revolved_edge_face(g, &source, axis, angle)
}

fn add_partial_revolved_edge_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    source: &RevolvedSourceEdge,
    axis: Axis3,
    angle: Rad64,
) -> Result<FaceKey, RevolveError> {
    validate_revolvable_radii(axis, source)?;

    let start = source.start.point;
    let end = source.end.point;
    let rotated_start = rotate_point(axis, start, angle);
    let rotated_end = rotate_point(axis, end, angle);
    let rotated_curve = rotate_curve(source.dart, &source.curve, axis, angle)?;
    let interval = source.curve.parameters_between(start, end);
    let surface = Surface::Revolution(SurfaceOfRevolution::new(source.curve.clone(), axis));

    let bottom_start = source.dart;
    let bottom_end = g.alpha(Dim::Zero, bottom_start);
    let end_arc_start = g.add_dart();
    let end_arc_end = g.add_dart();
    let rotated_start_dart = g.add_dart();
    let rotated_end_dart = g.add_dart();
    let start_arc_start = g.add_dart();
    let start_arc_end = g.add_dart();

    g.link(Dim::Zero, end_arc_start, end_arc_end)?;
    g.link(Dim::Zero, rotated_start_dart, rotated_end_dart)?;
    g.link(Dim::Zero, start_arc_start, start_arc_end)?;

    g.link(Dim::One, bottom_end, end_arc_start)?;
    g.link(Dim::One, end_arc_end, rotated_start_dart)?;
    g.link(Dim::One, rotated_end_dart, start_arc_start)?;
    g.link(Dim::One, start_arc_end, bottom_start)?;

    g.add_vertex(VertexAttr::new(end_arc_end, rotated_end, P::V::default()));
    g.add_vertex(VertexAttr::new(
        rotated_end_dart,
        rotated_start,
        P::V::default(),
    ));

    g.add_edge(EdgeAttr::new(
        end_arc_start,
        revolve_circle_curve(axis, end, angle),
        P::E::default(),
    ));
    g.add_edge(EdgeAttr::new(
        rotated_end_dart,
        rotated_curve,
        P::E::default(),
    ));
    g.add_edge(EdgeAttr::new(
        start_arc_end,
        revolve_circle_curve(axis, start, angle),
        P::E::default(),
    ));

    let mut pcurves = HashMap::with_capacity(4);
    pcurves.insert(
        bottom_start,
        Curve2::Line(Line2::new(
            Point2::new(interval.start, 0.0),
            Point2::new(interval.end, 0.0),
        )),
    );
    pcurves.insert(
        end_arc_start,
        Curve2::Line(Line2::new(
            Point2::new(interval.end, 0.0),
            Point2::new(interval.end, angle.val()),
        )),
    );
    pcurves.insert(
        rotated_start_dart,
        Curve2::Line(Line2::new(
            Point2::new(interval.end, angle.val()),
            Point2::new(interval.start, angle.val()),
        )),
    );
    pcurves.insert(
        start_arc_start,
        Curve2::Line(Line2::new(
            Point2::new(interval.start, angle.val()),
            Point2::new(interval.start, 0.0),
        )),
    );

    g.add_profile(ProfileAttr::new(bottom_start, P::Profile::default()));
    Ok(g.add_face(FaceAttr::with_pcurves(
        surface,
        P::F::default(),
        bottom_start,
        Vec::new(),
        pcurves,
    )))
}

fn add_full_revolved_edge_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    source: &RevolvedSourceEdge,
    axis: Axis3,
    angle: Rad64,
) -> Result<FaceKey, RevolveError> {
    if source.start.key == source.end.key {
        return Err(RevolveError::BoundarylessFullRevolve { key: source.key });
    }

    let start_on_axis = revolve_radius(axis, source.start.point) <= LINEAR_TOLERANCE;
    let end_on_axis = revolve_radius(axis, source.end.point) <= LINEAR_TOLERANCE;
    if start_on_axis && end_on_axis {
        return add_full_revolved_apex_to_apex_face(g, source, axis, angle);
    }

    add_full_revolved_open_edge_face(g, source, axis, angle)
}

/// Closes an apex-to-apex revolution by identifying its two meridian seams.
///
/// The face starts as a two-edge loop containing the source meridian and its
/// full-turn copy. Sewing those occurrences in dimension two leaves one edge
/// incident twice to one face while preserving the two pole vertices.
fn add_full_revolved_apex_to_apex_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    source: &RevolvedSourceEdge,
    axis: Axis3,
    angle: Rad64,
) -> Result<FaceKey, RevolveError> {
    validate_consumable_source_edge(g, source)?;
    let interval = source
        .curve
        .parameters_between(source.start.point, source.end.point);
    let middle = source.curve.point_at(0.5 * (interval.start + interval.end));
    if revolve_radius(axis, middle) <= LINEAR_TOLERANCE {
        return Err(RevolveError::EdgeOnRevolutionAxis { key: source.key });
    }

    let seam_start = source.dart;
    let seam_end = g.alpha(Dim::Zero, seam_start);
    let opposite_end = g.add_dart();
    let opposite_start = g.add_dart();
    g.link(Dim::Zero, opposite_start, opposite_end)?;
    g.link(Dim::One, seam_end, opposite_end)?;
    g.link(Dim::One, opposite_start, seam_start)?;

    g.add_edge(EdgeAttr::new(
        opposite_start,
        source.curve.clone(),
        P::E::default(),
    ));
    if Profile::from_dart(g, seam_start).is_none() {
        g.add_profile(ProfileAttr::new(seam_start, P::Profile::default()));
    }

    let mut pcurves = HashMap::with_capacity(2);
    pcurves.insert(
        seam_start,
        Curve2::Line(Line2::new(
            Point2::new(interval.start, 0.0),
            Point2::new(interval.end, 0.0),
        )),
    );
    pcurves.insert(
        opposite_end,
        Curve2::Line(Line2::new(
            Point2::new(interval.end, angle.val()),
            Point2::new(interval.start, angle.val()),
        )),
    );
    let face = g.add_face(FaceAttr::with_pcurves(
        Surface::Revolution(SurfaceOfRevolution::new(source.curve.clone(), axis)),
        P::F::default(),
        seam_start,
        Vec::new(),
        pcurves,
    ));

    sew_revolved_alpha2_edges(g, seam_start, opposite_start, seam_start, opposite_start)?;
    Ok(face)
}

fn add_full_revolved_open_edge_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    source: &RevolvedSourceEdge,
    axis: Axis3,
    angle: Rad64,
) -> Result<FaceKey, RevolveError> {
    let interval = source
        .curve
        .parameters_between(source.start.point, source.end.point);
    let surface = Surface::Revolution(SurfaceOfRevolution::new(source.curve.clone(), axis));
    let start_radius = revolve_radius(axis, source.start.point);
    let end_radius = revolve_radius(axis, source.end.point);

    validate_consumable_source_edge(g, source)?;

    let reuse_start = start_radius > LINEAR_TOLERANCE;
    let reused_loop_point = if reuse_start {
        source.start.point
    } else if end_radius > LINEAR_TOLERANCE {
        source.end.point
    } else {
        return Err(RevolveError::BoundarylessFullRevolve { key: source.key });
    };
    let reused_loop = consume_source_edge_as_closed_loop(
        g,
        source,
        reused_loop_point,
        revolve_circle_curve(axis, reused_loop_point, angle),
    )?;

    let start_loop = (start_radius > LINEAR_TOLERANCE)
        .then(|| {
            if reuse_start {
                Ok(reused_loop)
            } else {
                add_closed_revolve_boundary_loop(
                    g,
                    source.start.point,
                    revolve_circle_curve(axis, source.start.point, angle),
                )
            }
        })
        .transpose()?
        .map(|dart| (dart, interval.start, start_radius));
    let end_loop = (end_radius > LINEAR_TOLERANCE)
        .then(|| {
            if !reuse_start {
                Ok(reused_loop)
            } else {
                add_closed_revolve_boundary_loop(
                    g,
                    source.end.point,
                    revolve_circle_curve(axis, source.end.point, angle),
                )
            }
        })
        .transpose()?
        .map(|dart| (dart, interval.end, end_radius));

    let (outer_loop, outer_u, inner_loop) = match (start_loop, end_loop) {
        (Some(start), Some(end)) if start.2 >= end.2 => (start.0, start.1, Some(end)),
        (Some(start), Some(end)) => (end.0, end.1, Some(start)),
        (Some(boundary), None) | (None, Some(boundary)) => (boundary.0, boundary.1, None),
        (None, None) => {
            return Err(RevolveError::BoundarylessFullRevolve { key: source.key });
        }
    };

    let mut pcurves = HashMap::with_capacity(1 + usize::from(inner_loop.is_some()));
    pcurves.insert(
        outer_loop,
        Curve2::Line(Line2::new(
            Point2::new(outer_u, 0.0),
            Point2::new(outer_u, angle.val()),
        )),
    );
    let inner_loops = inner_loop
        .map(|(dart, u, _)| {
            pcurves.insert(
                dart,
                Curve2::Line(Line2::new(Point2::new(u, angle.val()), Point2::new(u, 0.0))),
            );
            vec![dart]
        })
        .unwrap_or_default();

    Ok(g.add_face(FaceAttr::with_pcurves(
        surface,
        P::F::default(),
        outer_loop,
        inner_loops,
        pcurves,
    )))
}

fn validate_consumable_source_edge<P: Payload>(
    g: &TopologyEdit<'_, P>,
    source: &RevolvedSourceEdge,
) -> Result<(), RevolveError> {
    let start = source.dart;
    let end = g.alpha(Dim::Zero, start);
    let edge = Edge::from_dart(g, start).ok_or(RevolveError::MissingEdge { key: source.key })?;
    let attached_to_face = !edge.faces().is_empty();
    let has_other_links = [Dim::One, Dim::Two, Dim::Three]
        .into_iter()
        .any(|dim| !g.is_free(start, dim) || !g.is_free(end, dim));
    if start == end || attached_to_face || has_other_links {
        return Err(RevolveError::SourceEdgeNotIsolated { key: source.key });
    }

    Ok(())
}

fn consume_source_edge_as_closed_loop<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    source: &RevolvedSourceEdge,
    point: Point3,
    curve: Curve,
) -> Result<Dart, RevolveError> {
    let start = source.dart;
    let end = g.alpha(Dim::Zero, start);

    let profile = Profile::from_dart(g, start).map(|profile| profile.key());
    if let Some(profile) = profile {
        g.remove_profile(profile);
    }
    g.remove_edge(source.key)
        .expect("validated source edge should remain registered");
    g.remove_vertex(source.start.key)
        .expect("validated source start vertex should remain registered");
    g.remove_vertex(source.end.key)
        .expect("validated source end vertex should remain registered");

    g.link(Dim::One, start, end)?;
    g.add_vertex(VertexAttr::new(start, point, P::V::default()));
    g.add_edge(EdgeAttr::new(start, curve, P::E::default()));
    g.add_profile(ProfileAttr::new(start, P::Profile::default()));
    Ok(start)
}

fn add_closed_revolve_boundary_loop<P: Payload>(
    edit: &mut TopologyEdit<'_, P>,
    point: Point3,
    curve: Curve,
) -> Result<Dart, TopologyEditError> {
    let first = edit.add_dart();
    let second = edit.add_dart();
    edit.link(Dim::Zero, first, second)?;
    edit.link(Dim::One, first, second)?;
    edit.add_vertex(VertexAttr::new(first, point, P::V::default()));
    edit.add_edge(EdgeAttr::new(first, curve, P::E::default()));
    edit.add_profile(ProfileAttr::new(first, P::Profile::default()));
    Ok(first)
}

/// Rotates an edge curve, keeping its parameterisation.
///
/// Rebuilding the curve from sampled endpoints instead would re-parameterise
/// it, so the rotated edge would no longer agree with the parameter interval
/// the caller computed on the source curve.
fn rotate_curve(
    dart: Dart,
    curve: &Curve,
    axis: Axis3,
    angle: Rad64,
) -> Result<Curve, RevolveError> {
    curve
        .rotated(axis, angle.val())
        .map_err(|source| RevolveError::RotationFailed { dart, source })
}

fn rotate_point(axis: Axis3, point: Point3, angle: Rad64) -> Point3 {
    axis.origin + Rotation3::from_axis_angle(&axis.direction, angle.val()) * (point - axis.origin)
}

fn is_full_turn(angle: Rad64) -> bool {
    (angle.val() - Rad64::FULL_TURN.val()).abs() <= ANGULAR_TOLERANCE
}

/// Revolves every edge of a planar profile into a sheet of lateral faces.
///
/// Adjacent generated faces are sewn along their swept vertex trajectories; a
/// closed source profile also closes the ring between its last and first faces.
/// The source profile remains in the map and is not used as sheet boundary
/// topology. `angle` is clamped between zero and one full turn.
///
/// Returns an error if the profile is not planar, required edge or vertex
/// geometry is missing, a source curve is unsupported, or generated faces
/// cannot be sewn.
///
/// # Panics
///
/// Panics if `profile` does not identify a registered profile.
pub fn add_revolved_profile<P: Payload>(
    g: &mut GMap<P>,
    profile: ProfileKey,
    axis: Axis3,
    angle: Rad64,
) -> Result<SheetKey, RevolveError> {
    let profile_dart = g.profile_unchecked(profile).dart;
    add_revolved_profile_from_dart(g, profile_dart, axis, angle)
}

/// Revolves a profile from an oriented traversal dart for internal callers.
pub(crate) fn add_revolved_profile_from_dart<P: Payload>(
    g: &mut GMap<P>,
    profile_dart: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<SheetKey, RevolveError> {
    g.transaction(|g| add_revolved_profile_from_dart_staged(g, profile_dart, axis, angle))
}

fn add_revolved_profile_from_dart_staged<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    profile_dart: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<SheetKey, RevolveError> {
    let profile = Profile::from_dart(g, profile_dart)
        .expect("profile dart must belong to a registered profile");
    let planar = Planar::new(profile).map_err(RevolveError::PlanarError)?;
    let close_ring = planar.inner().is_closed();
    let dart = add_revolved_profile_faces(g, profile_dart, axis, angle, close_ring)?.swept_dart;
    Ok(g.add_sheet(SheetAttr::new(dart, P::Sheet::default())))
}

struct RevolvedProfile {
    swept_dart: Dart,
    bottom_edges: Vec<Dart>,
    top_edges: Vec<Dart>,
    faces: Vec<FaceKey>,
}

struct RevolvedFace {
    /// Dart of the un-rotated source edge, sitting at the source `start` vertex.
    bottom_edge: Dart,
    /// Dart of the rotated edge, sitting at the rotated `start` vertex.
    ///
    /// The quad loop traverses the rotated edge backwards (`rotated_end` to
    /// `rotated_start`), so this is the *second* dart of that edge rather than
    /// the loop-order one. Keeping it at `rotated_start` makes it line up with
    /// the matching cap edge dart, which also sits at `rotated_start`.
    top_edge: Dart,
    start_side: Dart,
    end_side: Dart,
    outer_loop: Dart,
    key: FaceKey,
}

fn add_revolved_profile_faces<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    profile_dart: Dart,
    axis: Axis3,
    angle: Rad64,
    close_ring: bool,
) -> Result<RevolvedProfile, RevolveError> {
    let angle = angle.clamp(Angle::ZERO, Angle::FULL_TURN);
    let profile = Profile::from_dart(g, profile_dart)
        .expect("profile dart must belong to a registered profile");
    let source_edges = profile
        .edges()
        .into_iter()
        .map(RevolvedSourceEdge::from_edge)
        .collect::<Result<Vec<_>, _>>()?;

    let mut faces = Vec::with_capacity(source_edges.len());
    for source in &source_edges {
        faces.push(add_revolved_edge_face(g, source, axis, angle)?);
    }

    sew_revolved_faces(g, &faces, close_ring)?;
    let swept_dart = faces.first().map_or(profile_dart, |face| face.outer_loop);
    Ok(RevolvedProfile {
        swept_dart,
        bottom_edges: faces.iter().map(|face| face.bottom_edge).collect(),
        top_edges: faces.iter().map(|face| face.top_edge).collect(),
        faces: faces.iter().map(|face| face.key).collect(),
    })
}

fn add_revolved_edge_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    source: &RevolvedSourceEdge,
    axis: Axis3,
    angle: Rad64,
) -> Result<RevolvedFace, RevolveError> {
    validate_revolvable_radii(axis, source)?;

    let start = source.start.point;
    let end = source.end.point;
    let curve = source.curve.clone();
    let rotated_start = rotate_point(axis, start, angle);
    let rotated_end = rotate_point(axis, end, angle);
    let rotated_curve = rotate_curve(source.dart, &curve, axis, angle)?;
    let start_arc = revolve_circle_curve(axis, start, angle);
    let end_arc = revolve_circle_curve(axis, end, angle);
    let interval = curve.parameters_between(start, end);
    let surface = Surface::Revolution(SurfaceOfRevolution::new(curve.clone(), axis));
    let pcurves = [
        (
            Point2::new(interval.start, 0.0),
            Point2::new(interval.end, 0.0),
        ),
        (
            Point2::new(interval.end, 0.0),
            Point2::new(interval.end, angle.val()),
        ),
        (
            Point2::new(interval.end, angle.val()),
            Point2::new(interval.start, angle.val()),
        ),
        (
            Point2::new(interval.start, angle.val()),
            Point2::new(interval.start, 0.0),
        ),
    ];

    add_revolved_quad_face(
        g,
        [start, end, rotated_end, rotated_start],
        [curve, end_arc, rotated_curve, start_arc],
        surface,
        pcurves,
    )
}

fn add_revolved_quad_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    corners: [Point3; 4],
    boundary_curves: [Curve; 4],
    surface: Surface,
    pcurves: [(Point2, Point2); 4],
) -> Result<RevolvedFace, RevolveError> {
    let darts: Vec<Dart> = (0..8).map(|_| g.add_dart()).collect();

    for i in 0..4 {
        g.link(Dim::Zero, darts[2 * i], darts[2 * i + 1])?;
    }
    for i in 0..4 {
        g.link(Dim::One, darts[2 * i + 1], darts[(2 * i + 2) % darts.len()])?;
    }

    for i in 0..4 {
        let dart = g.cell_representative(darts[2 * i], Dim::Zero);
        g.add_vertex(VertexAttr::new(dart, corners[i], P::V::default()));
    }

    for i in 0..4 {
        let edge_dart = darts[2 * i];
        g.add_edge(EdgeAttr::new(
            edge_dart,
            boundary_curves[i].clone(),
            P::E::default(),
        ));
    }

    g.add_profile(ProfileAttr::new(darts[0], P::Profile::default()));
    let key = g.add_face(FaceAttr::with_pcurves(
        surface,
        P::F::default(),
        darts[0],
        Vec::new(),
        quad_pcurves(&pcurves, &darts),
    ));

    Ok(RevolvedFace {
        bottom_edge: darts[0],
        // darts[4] is at `rotated_end`; darts[5] is its alpha0 partner at
        // `rotated_start`, which is the vertex the cap edge dart carries.
        top_edge: darts[5],
        start_side: darts[7],
        end_side: darts[2],
        outer_loop: darts[0],
        key,
    })
}

fn sew_revolved_faces<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    faces: &[RevolvedFace],
    close_ring: bool,
) -> Result<(), RevolveError> {
    for i in 0..faces.len().saturating_sub(1) {
        sew_revolved_side_edges(g, faces[i].end_side, faces[i + 1].start_side)?;
    }

    if close_ring && !faces.is_empty() {
        sew_revolved_side_edges(g, faces[0].start_side, faces[faces.len() - 1].end_side)?;
    }

    Ok(())
}

struct Alpha2RevolveMerge {
    survivor_edge: EdgeKey,
    removed_edge: EdgeKey,
    survivor_start: VertexKey,
    removed_start: VertexKey,
    survivor_end: VertexKey,
    removed_end: VertexKey,
}

fn sew_revolved_side_edges<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    survivor: Dart,
    removed: Dart,
) -> Result<(), RevolveError> {
    sew_revolved_alpha2_edges(g, survivor, removed, survivor, removed)
}

pub(crate) fn sew_revolved_alpha2_edges<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    first: Dart,
    second: Dart,
    survivor: Dart,
    removed: Dart,
) -> Result<(), RevolveError> {
    let merge = alpha2_revolve_merge(g, first, second, survivor, removed)?;
    g.sew(Dim::Two, first, second)
        .map_err(|_| RevolveError::SewFailed {
            dim: Dim::Two,
            first,
            second,
        })?;
    if merge.survivor_edge != merge.removed_edge {
        g.merge_edges_into(merge.survivor_edge, merge.removed_edge);
    }
    let mut removed_vertices = Vec::new();
    if merge.survivor_start != merge.removed_start {
        g.merge_vertices_into(merge.survivor_start, merge.removed_start);
        removed_vertices.push(merge.removed_start);
    }
    if merge.survivor_end != merge.removed_end && !removed_vertices.contains(&merge.removed_end) {
        g.merge_vertices_into(merge.survivor_end, merge.removed_end);
    }
    Ok(())
}

fn alpha2_revolve_merge<P: Payload>(
    g: &GMap<P>,
    first: Dart,
    second: Dart,
    survivor: Dart,
    removed: Dart,
) -> Result<Alpha2RevolveMerge, RevolveError> {
    let first_edge =
        Edge::from_dart(g, first).ok_or(RevolveError::MissingEdgeCurve { dart: first })?;
    let second_edge =
        Edge::from_dart(g, second).ok_or(RevolveError::MissingEdgeCurve { dart: second })?;

    if survivor == first && removed == second {
        return Ok(Alpha2RevolveMerge {
            survivor_edge: first_edge.key(),
            removed_edge: second_edge.key(),
            survivor_start: first_edge.start().key(),
            removed_start: second_edge.start().key(),
            survivor_end: first_edge.end().key(),
            removed_end: second_edge.end().key(),
        });
    }

    if survivor == second && removed == first {
        return Ok(Alpha2RevolveMerge {
            survivor_edge: second_edge.key(),
            removed_edge: first_edge.key(),
            survivor_start: second_edge.start().key(),
            removed_start: first_edge.start().key(),
            survivor_end: second_edge.end().key(),
            removed_end: first_edge.end().key(),
        });
    }

    Err(RevolveError::MissingEdgeCurve { dart: survivor })
}

/// Returns the trajectory swept by `point` turning `angle` around `axis`.
///
/// A partial turn yields a bounded arc running from `point` at parameter `0`
/// to its rotated image at parameter `1`. A full turn yields the closed circle
/// itself, because a closed edge needs the periodic curve that
/// [`Curve::parameters_between`] can span over a whole period.
fn revolve_circle_curve(axis: Axis3, point: Point3, angle: Rad64) -> Curve {
    let projected = axis.project(point);
    let radius = distance(&projected, &point);
    let plane = if radius <= LINEAR_TOLERANCE {
        Circle::from_axis(Axis3::new(projected, axis.direction), radius)
            .plane()
            .clone()
    } else {
        Plane::new(projected, point - projected, axis.direction)
    };

    if is_full_turn(angle) {
        return Curve::circle(plane, radius);
    }

    Curve::arc(plane, radius, Interval::new(0.0, angle.val()))
}

/// Rejects source edges that cannot sweep a well-formed face.
fn validate_revolvable_radii(axis: Axis3, source: &RevolvedSourceEdge) -> Result<(), RevolveError> {
    let start_on_axis = revolve_radius(axis, source.start.point) <= LINEAR_TOLERANCE;
    let end_on_axis = revolve_radius(axis, source.end.point) <= LINEAR_TOLERANCE;
    match (start_on_axis, end_on_axis) {
        (true, true) => Err(RevolveError::EdgeOnRevolutionAxis { key: source.key }),
        (true, false) | (false, true) => {
            Err(RevolveError::ApexRevolveUnsupported { key: source.key })
        }
        (false, false) => Ok(()),
    }
}

fn revolve_radius(axis: Axis3, point: Point3) -> f64 {
    distance(&axis.project(point), &point)
}

fn quad_pcurves(uv: &[(Point2, Point2); 4], darts: &[Dart]) -> HashMap<Dart, Curve2> {
    let mut pcurves = HashMap::with_capacity(4);
    for i in 0..4 {
        pcurves.insert(darts[2 * i], Curve2::Line(Line2::new(uv[i].0, uv[i].1)));
    }
    pcurves
}

/// Revolves an existing face into a solid around `axis`.
///
/// For a partial turn, the source face and a rotated copy form the caps and the
/// revolved boundary loops form the lateral shell. A full turn omits coincident
/// caps and builds the shell directly from the face's outer and inner loops.
/// `angle` is clamped between zero and one full turn.
///
/// Returns an error if the face is missing, its loops cannot be revolved, a
/// partial turn uses an unsupported cap surface, or generated topology cannot
/// be sewn.
pub fn add_revolved_face<P: Payload>(
    g: &mut GMap<P>,
    face_key: FaceKey,
    axis: Axis3,
    angle: Rad64,
) -> Result<SolidKey, RevolveError> {
    g.transaction(|g| add_revolved_face_staged(g, face_key, axis, angle))
}

/// Builds caps and lateral sheets, then registers the resulting staged solid.
fn add_revolved_face_staged<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    face_key: FaceKey,
    axis: Axis3,
    angle: Rad64,
) -> Result<SolidKey, RevolveError> {
    let angle = angle.clamp(Angle::ZERO, Angle::FULL_TURN);
    let face = g
        .face_attr(face_key)
        .map(|attr| attr.face(g))
        .ok_or(RevolveError::MissingFace { key: face_key })?;
    let mut loops = Vec::with_capacity(1 + face.inner_loops().len());
    loops.push(face.outer_loop().dart);
    loops.extend(face.inner_loops().into_iter().map(|loop_| loop_.dart));

    let sweep = revolve_sweep_direction(axis, &face);
    let cap_faces_sweep = face.normal_at(0.0, 0.0).dot(&sweep);

    if is_full_turn(angle) {
        return add_full_revolved_face(g, face_key, loops, axis, angle, cap_faces_sweep);
    }

    let rotated_face = rotate_face(&face, axis, angle)?;
    let top_face_dart = g.merge(rotated_face.face());
    let top_face_key = *g.attribute_unchecked::<Cell2>(top_face_dart);
    let top_face_attr = g.face_attr_unchecked(top_face_key);
    let mut top_loops = Vec::with_capacity(1 + top_face_attr.inner_loops.len());
    top_loops.push(top_face_attr.outer_loop);
    top_loops.extend(top_face_attr.inner_loops.iter().copied());

    let mut lateral_faces = Vec::new();
    for (bottom_loop, top_loop) in loops.into_iter().zip(top_loops) {
        let revolved = sew_revolved_loop_to_caps(g, bottom_loop, top_loop, axis, angle)?;
        lateral_faces.extend(revolved.faces);
    }

    orient_revolved_shell(g, face_key, top_face_key, &lateral_faces, cap_faces_sweep);

    // Contextual, like the extruded shell: it must keep the outward
    // orientation just established for the source cap.
    let shell = g.face_attr_unchecked(face_key).outer_loop;
    if g.sheet_key(shell).is_none() {
        g.add_sheet(SheetAttr::new(shell, P::Sheet::default()));
    }
    Ok(g.add_solid(SolidAttr::new(P::S::default(), shell, None)))
}

/// Returns the direction the revolution sweeps a point of `face`, `axis x r`.
fn revolve_sweep_direction<P: Payload>(axis: Axis3, face: &Face<'_, P>) -> Vector3<f64> {
    let point = face
        .outer_loop()
        .edges()
        .first()
        .and_then(|edge| edge.start().point().copied())
        .unwrap_or(axis.origin);
    axis.direction.cross(&(point - axis.project(point)))
}

/// Makes every face of a revolved shell point away from the material.
///
/// The cap at angle zero must face against the sweep, so exactly one of the two
/// caps is reversed. The lateral faces carry `dS/du x dS/dv`, which points at
/// the inside of the swept region precisely when the source cap already faces
/// against the sweep, so they flip together with the far cap.
fn orient_revolved_shell<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    bottom_face: FaceKey,
    top_face: FaceKey,
    lateral_faces: &[FaceKey],
    bottom_normal_dot_sweep: f64,
) {
    if bottom_normal_dot_sweep > LINEAR_TOLERANCE {
        reverse_face_winding(g, bottom_face);
        return;
    }

    reverse_face_winding(g, top_face);
    for &face in lateral_faces {
        reverse_face_winding(g, face);
    }
}

/// Builds the shell of a full turn, which has no caps.
///
/// Every lateral face closes onto itself along the seam at angle zero, so the
/// swept edge at the end of the turn is sewn back to the one at its start. The
/// source face is then dropped: it is interior to the solid, and its boundary
/// wire survives only as the loops the lateral faces were built from.
fn add_full_revolved_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    face_key: FaceKey,
    loops: Vec<Dart>,
    axis: Axis3,
    angle: Rad64,
    source_normal_dot_sweep: f64,
) -> Result<SolidKey, RevolveError> {
    let mut shell = None;
    let mut lateral_faces = Vec::new();
    for &loop_dart in &loops {
        let revolved = add_revolved_profile_faces(g, loop_dart, axis, angle, true)?;
        sew_full_revolved_seam(g, &revolved)?;
        lateral_faces.extend(revolved.faces);
        shell.get_or_insert(revolved.swept_dart);
    }

    if source_normal_dot_sweep <= LINEAR_TOLERANCE {
        for &face in &lateral_faces {
            reverse_face_winding(g, face);
        }
    }

    let shell = shell.expect("a face should have at least one boundary loop");
    let shell = consume_revolved_source_face(g, face_key, &loops, shell)?;
    if g.sheet_key(shell).is_none() {
        g.add_sheet(SheetAttr::new(shell, P::Sheet::default()));
    }
    Ok(g.add_solid(SolidAttr::new(P::S::default(), shell, None)))
}

/// Deletes the source face and its boundary wire after a full turn.
///
/// A full turn leaves the source geometry strictly inside the solid, where a
/// leftover face and dangling wire would be counted by every cell traversal.
/// Removing darts compacts the map, so `shell` is returned remapped.
fn consume_revolved_source_face<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    face_key: FaceKey,
    loops: &[Dart],
    shell: Dart,
) -> Result<Dart, RevolveError> {
    g.remove_face(face_key);

    let mut darts = Vec::new();
    for &loop_dart in loops {
        let profile =
            Profile::from_dart(g, loop_dart).expect("source loop must have a registered profile");
        let profile_key = profile.key();
        let loop_darts = profile.darts().collect::<Vec<_>>();
        for dart in loop_darts.iter().copied().step_by(2) {
            if let Some(edge) = Edge::from_dart(g, dart) {
                let (edge_key, vertex_key) = (edge.key(), edge.start().key());
                g.remove_edge(edge_key);
                g.remove_vertex(vertex_key);
            }
        }
        g.remove_profile(profile_key);
        darts.extend(loop_darts);
    }

    for &dart in &darts {
        for dim in [Dim::Zero, Dim::One, Dim::Two, Dim::Three] {
            if !g.is_free(dart, dim) {
                g.unlink(dim, dart)?;
            }
        }
    }

    let isolated = darts.into_iter().map(IsolatedDart::new).collect();
    let remapped = g.remove_isolated_darts(isolated);
    Ok(remapped.get(&shell).copied().unwrap_or(shell))
}

/// Sews the seam of a full turn, where the swept copy of each source edge lands
/// back on the source edge itself.
fn sew_full_revolved_seam<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    revolved: &RevolvedProfile,
) -> Result<(), RevolveError> {
    for (&bottom, &top) in revolved.bottom_edges.iter().zip(revolved.top_edges.iter()) {
        sew_revolved_alpha2_edges(g, bottom, top, bottom, top)?;
    }

    Ok(())
}

fn sew_revolved_loop_to_caps<P: Payload>(
    g: &mut TopologyEdit<'_, P>,
    bottom_loop: Dart,
    top_loop: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<RevolvedProfile, RevolveError> {
    let bottom_edges = Profile::from_dart(g, bottom_loop)
        .expect("bottom loop must have a registered profile")
        .edges()
        .into_iter()
        .map(|edge| edge.dart())
        .collect::<Vec<_>>();
    let top_edges = Profile::from_dart(g, top_loop)
        .expect("top loop must have a registered profile")
        .edges()
        .into_iter()
        .map(|edge| edge.dart())
        .collect::<Vec<_>>();
    let revolved = add_revolved_profile_faces(g, bottom_loop, axis, angle, true)?;

    // `Profile::edges` yields the dart at each edge's traversal start, and
    // `Edge::start` is the vertex at that dart, so an alpha2 sew is only
    // vertex-correct when both darts sit on the same 3D point. `bottom_edge`
    // and `top_edge` are chosen to satisfy that against the cap loop darts.
    for (&cap_edge, &side_edge) in bottom_edges.iter().zip(revolved.bottom_edges.iter()) {
        sew_revolved_alpha2_edges(g, side_edge, cap_edge, cap_edge, side_edge)?;
    }
    for (&cap_edge, &side_edge) in top_edges.iter().zip(revolved.top_edges.iter()) {
        sew_revolved_alpha2_edges(g, side_edge, cap_edge, cap_edge, side_edge)?;
    }

    Ok(revolved)
}

fn rotate_face<P: Payload>(
    face: &Face<'_, P>,
    axis: Axis3,
    angle: Rad64,
) -> Result<Shape<FaceTag, P>, RevolveError> {
    let (mut rotated, rotated_dart) = face.isolate();

    let vertex_keys = rotated
        .iter_vertices()
        .map(|(key, _)| key)
        .collect::<Vec<_>>();
    let edge_keys = rotated.iter_edges().map(|(key, _)| key).collect::<Vec<_>>();
    let rotated_face_key = *rotated.attribute_unchecked::<Cell2>(rotated_dart);
    rotated.transaction(|edit| {
        for key in vertex_keys {
            let vertex = edit.vertex_attr_mut_unchecked(key);
            vertex.point = rotate_point(axis, vertex.point, angle);
        }

        for key in edge_keys {
            let edge = edit.edge_attr_mut_unchecked(key);
            edge.curve = rotate_curve(edge.dart, &edge.curve, axis, angle)?;
        }

        let rotated_face = edit.face_attr_mut_unchecked(rotated_face_key);
        rotated_face.surface =
            rotate_surface(rotated_face.outer_loop, &rotated_face.surface, axis, angle)?;
        Ok::<_, RevolveError>(())
    })?;

    Ok(Shape::new(rotated, rotated_face_key))
}

/// Rotates a face's support surface, keeping its parameterisation so the
/// face's existing pcurves stay valid on the rotated copy.
fn rotate_surface(
    dart: Dart,
    surface: &Surface,
    axis: Axis3,
    angle: Rad64,
) -> Result<Surface, RevolveError> {
    surface
        .rotated(axis, angle.val())
        .map_err(|source| RevolveError::RotationFailed { dart, source })
}

/// Returns the key of the face incident to `dart`, if the dart belongs to one.
pub fn face_key_for_dart<P: Payload>(g: &GMap<P>, dart: Dart) -> Option<FaceKey> {
    g.attribute::<Cell2>(dart).copied()
}
