use std::collections::HashMap;

use nalgebra::{Rotation3, distance};
use radians::{Angle, Rad64};
use thiserror::Error;

use crate::builders::profiles::add_edge;
use crate::geometry::axis::Axis3;
use crate::geometry::{
    ANGULAR_TOLERANCE, Circle, Curve, Curve2, LINEAR_TOLERANCE, Line, Line2, Plane, Point2, Point3,
    Surface, SurfaceOfRevolution,
};
use crate::topology::attributes::{EdgeAttr, FaceAttr, SolidAttr, VertexAttr};
use crate::topology::closed::Closeable;
use crate::topology::edge::Edge;
use crate::topology::face::Face;
use crate::topology::gmap::{Cell2, Dart, Dim, GMap, MergeTopology};
use crate::topology::payload::Payload;
use crate::topology::planar::{Planar, PlanarityError};
use crate::topology::profile::Profile;
use crate::topology::shape::{FaceShape, Shape};
use crate::topology::shape_keys::{FaceKey, SolidKey};

#[derive(Debug, Error)]
pub enum RevolveError {
    #[error("The provided profile is not planar")]
    PlanarError(PlanarityError),

    #[error("Missing vertex point for dart {dart:?}")]
    MissingVertexPoint { dart: Dart },

    #[error("Missing edge curve for dart {dart:?}")]
    MissingEdgeCurve { dart: Dart },

    #[error("Missing face for key {key:?}")]
    MissingFace { key: FaceKey },

    #[error("Only line edges can be partially revolved for now: {dart:?}")]
    UnsupportedPartialRevolveCurve { dart: Dart },

    #[error("Only planar cap faces can be partially revolved for now: {dart:?}")]
    UnsupportedPartialRevolveSurface { dart: Dart },

    #[error("Darts {first:?} and {second:?} are not sewable in dimension {dim:?}")]
    SewFailed { dim: Dim, first: Dart, second: Dart },
}

/// Adds the circular sweep topology generated by revolving one edge around `axis`.
///
/// Full revolutions are handled as a special case: the two source vertices each
/// get a closed circular edge, with no duplicate endpoint vertices. Partial
/// revolutions create a swept quad using the source edge as the first boundary,
/// two circular side edges, and a rotated copy of the source edge.
pub fn add_revolved_edge<P: Payload>(
    g: &mut GMap<P>,
    edge_dart: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<Dart, RevolveError> {
    let angle = angle.clamp(Angle::ZERO, Angle::FULL_TURN);
    if is_full_turn(angle) {
        return add_full_revolved_edge(g, edge_dart, axis);
    }

    add_partial_revolved_edge(g, edge_dart, axis, angle)
}

fn add_full_revolved_edge<P: Payload>(
    g: &mut GMap<P>,
    edge_dart: Dart,
    axis: Axis3,
) -> Result<Dart, RevolveError> {
    let vertices = edge_vertices(g, edge_dart)?;
    let mut circles = vertices
        .into_iter()
        .map(|(dart, point)| add_closed_revolve_circle(g, dart, axis, point));
    let first = circles
        .next()
        .expect("an edge always has at least one incident vertex")?;

    for circle in circles {
        circle?;
    }

    Ok(first)
}

fn add_partial_revolved_edge<P: Payload>(
    g: &mut GMap<P>,
    edge_dart: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<Dart, RevolveError> {
    let (start, end, curve, end_dart) = edge_geometry(g, edge_dart)?;
    let rotated_start = rotate_point(axis, start, angle);
    let rotated_end = rotate_point(axis, end, angle);
    let rotated_curve = rotate_curve(edge_dart, &curve, axis, angle)?;

    let start_arc = add_open_revolve_circle(g, axis, start, rotated_start)?;
    let end_arc = if same_vertex(start, end) {
        start_arc
    } else {
        add_open_revolve_circle(g, axis, end, rotated_end)?
    };
    let (rotated_edge, _) = add_edge(g, rotated_start, rotated_end, rotated_curve);
    let rotated_edge_end = g.alpha(Dim::Zero, rotated_edge);
    let start_arc_end = g.alpha(Dim::Zero, start_arc);
    let end_arc_end = g.alpha(Dim::Zero, end_arc);

    if end_arc != start_arc {
        sew(g, Dim::One, end_dart, end_arc)?;
        sew(g, Dim::One, end_arc_end, rotated_edge_end)?;
    }
    sew(g, Dim::One, rotated_edge, start_arc_end)?;
    sew(g, Dim::One, start_arc, edge_dart)?;

    Ok(rotated_edge)
}

fn add_open_revolve_circle<P: Payload>(
    g: &mut GMap<P>,
    axis: Axis3,
    start: Point3,
    end: Point3,
) -> Result<Dart, RevolveError> {
    Ok(add_edge(g, start, end, revolve_circle_curve(axis, start)).0)
}

fn add_closed_revolve_circle<P: Payload>(
    g: &mut GMap<P>,
    _source_vertex_dart: Dart,
    axis: Axis3,
    point: Point3,
) -> Result<Dart, RevolveError> {
    let projected = axis.project(point);
    let radius = distance(&projected, &point);
    let first = g.add_dart();
    let second = g.add_dart();
    g.sew_unchecked(Dim::Zero, first, second);
    g.sew_unchecked(Dim::One, first, second);
    g.add_vertex(VertexAttr::new(first, point, P::V::default()));
    g.add_edge(EdgeAttr::new(
        first,
        Curve::Circle(Circle::from_axis(
            Axis3::new(projected, axis.direction),
            radius,
        )),
        P::E::default(),
    ));
    Ok(first)
}

fn edge_geometry<P: Payload>(
    g: &GMap<P>,
    edge_dart: Dart,
) -> Result<(Point3, Point3, Curve, Dart), RevolveError> {
    let edge = Edge::new(g, edge_dart);
    let start = *edge
        .start()
        .point()
        .ok_or(RevolveError::MissingVertexPoint { dart: edge_dart })?;
    let end_dart = g.alpha(Dim::Zero, edge_dart);
    let end = *edge
        .end()
        .point()
        .ok_or(RevolveError::MissingVertexPoint { dart: end_dart })?;
    let curve = edge
        .curve()
        .ok_or(RevolveError::MissingEdgeCurve { dart: edge_dart })?;
    Ok((start, end, curve.clone(), end_dart))
}

fn edge_vertices<P: Payload>(
    g: &GMap<P>,
    edge_dart: Dart,
) -> Result<Vec<(Dart, Point3)>, RevolveError> {
    let edge = Edge::new(g, edge_dart);
    edge.vertices()
        .into_iter()
        .map(|vertex| {
            let point = *vertex
                .point()
                .ok_or(RevolveError::MissingVertexPoint { dart: vertex.dart })?;
            Ok((vertex.dart, point))
        })
        .collect()
}

fn rotate_curve(
    dart: Dart,
    curve: &Curve,
    axis: Axis3,
    angle: Rad64,
) -> Result<Curve, RevolveError> {
    match curve {
        Curve::Line(_) => Ok(Curve::Line(Line::new(
            rotate_point(axis, curve.point_at(0.0), angle),
            rotate_point(axis, curve.point_at(1.0), angle),
        ))),
        Curve::Circle(_) | Curve::Nurbs(_) => {
            Err(RevolveError::UnsupportedPartialRevolveCurve { dart })
        }
    }
}

fn rotate_point(axis: Axis3, point: Point3, angle: Rad64) -> Point3 {
    axis.origin + Rotation3::from_axis_angle(&axis.direction, angle.val()) * (point - axis.origin)
}

fn is_full_turn(angle: Rad64) -> bool {
    (angle.val() - Rad64::FULL_TURN.val()).abs() <= ANGULAR_TOLERANCE
}

fn same_vertex(a: Point3, b: Point3) -> bool {
    (a - b).norm_squared() <= LINEAR_TOLERANCE * LINEAR_TOLERANCE
}

fn sew<P: Payload>(
    g: &mut GMap<P>,
    dim: Dim,
    first: Dart,
    second: Dart,
) -> Result<(), RevolveError> {
    g.sew(dim, first, second)
        .map_err(|_| RevolveError::SewFailed { dim, first, second })
}

pub fn add_revolved_profile<P: Payload>(
    g: &mut GMap<P>,
    profile_dart: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<Dart, RevolveError> {
    let profile = Profile::new(g, profile_dart);
    let planar = Planar::new(profile).map_err(RevolveError::PlanarError)?;
    let profile = planar.inner();
    if profile.is_closed() {
        return Ok(add_revolved_profile_faces(g, profile_dart, axis, angle, true)?.swept_dart);
    }

    Ok(add_revolved_profile_faces(g, profile_dart, axis, angle, false)?.swept_dart)
}

struct RevolvedProfile {
    swept_dart: Dart,
    bottom_edges: Vec<Dart>,
    top_edges: Vec<Dart>,
}

struct RevolvedFace {
    bottom_edge: Dart,
    top_edge: Dart,
    start_side: Dart,
    end_side: Dart,
    outer_loop: Dart,
}

fn add_revolved_profile_faces<P: Payload>(
    g: &mut GMap<P>,
    profile_dart: Dart,
    axis: Axis3,
    angle: Rad64,
    close_ring: bool,
) -> Result<RevolvedProfile, RevolveError> {
    let angle = angle.clamp(Angle::ZERO, Angle::FULL_TURN);
    let profile = Profile::new(g, profile_dart);
    let edge_darts = profile
        .edges()
        .into_iter()
        .map(|edge| edge.dart)
        .collect::<Vec<_>>();

    let mut faces = Vec::with_capacity(edge_darts.len());
    for edge_dart in edge_darts {
        faces.push(add_revolved_edge_face(g, edge_dart, axis, angle)?);
    }

    sew_revolved_faces(g, &faces, close_ring)?;
    let swept_dart = faces.first().map_or(profile_dart, |face| face.outer_loop);
    Ok(RevolvedProfile {
        swept_dart,
        bottom_edges: faces.iter().map(|face| face.bottom_edge).collect(),
        top_edges: faces.iter().map(|face| face.top_edge).collect(),
    })
}

fn add_revolved_edge_face<P: Payload>(
    g: &mut GMap<P>,
    edge_dart: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<RevolvedFace, RevolveError> {
    let (start, end, curve, _) = edge_geometry(g, edge_dart)?;
    let rotated_start = rotate_point(axis, start, angle);
    let rotated_end = rotate_point(axis, end, angle);
    let rotated_curve = rotate_curve(edge_dart, &curve, axis, angle)?;
    let start_arc = revolve_circle_curve(axis, start);
    let end_arc = revolve_circle_curve(axis, end);
    let (u0, u1) = curve.parameters_between(start, end);
    let surface = Surface::Revolution(SurfaceOfRevolution::new(
        curve.clone(),
        axis.origin,
        axis.direction,
    ));
    let pcurves = [
        (Point2::new(u0, 0.0), Point2::new(u1, 0.0)),
        (Point2::new(u1, 0.0), Point2::new(u1, angle.val())),
        (Point2::new(u1, angle.val()), Point2::new(u0, angle.val())),
        (Point2::new(u0, angle.val()), Point2::new(u0, 0.0)),
    ];

    add_revolved_quad_face(
        g,
        [start, end, rotated_end, rotated_start],
        [curve, end_arc, rotated_curve, start_arc],
        surface,
        pcurves,
    )
}

fn add_revolved_quad_face<P: Payload>(
    g: &mut GMap<P>,
    corners: [Point3; 4],
    boundary_curves: [Curve; 4],
    surface: Surface,
    pcurves: [(Point2, Point2); 4],
) -> Result<RevolvedFace, RevolveError> {
    let darts: Vec<Dart> = (0..8).map(|_| g.add_dart()).collect();

    for i in 0..4 {
        sew(g, Dim::Zero, darts[2 * i], darts[2 * i + 1])?;
    }
    for i in 0..4 {
        sew(
            g,
            Dim::One,
            darts[2 * i + 1],
            darts[(2 * i + 2) % darts.len()],
        )?;
    }

    for i in 0..4 {
        let dart = g.cell_representative(darts[2 * i], Dim::Zero);
        g.add_vertex(VertexAttr::new(dart, corners[i], P::V::default()));
    }

    for i in 0..4 {
        let edge_dart = g.cell_representative(darts[2 * i], Dim::One);
        g.add_edge(EdgeAttr::new(
            edge_dart,
            boundary_curves[i].clone(),
            P::E::default(),
        ));
    }

    g.add_face(FaceAttr::with_pcurves(
        surface,
        P::F::default(),
        darts[0],
        Vec::new(),
        quad_pcurves(&pcurves, &darts),
    ));

    Ok(RevolvedFace {
        bottom_edge: darts[0],
        top_edge: darts[4],
        start_side: darts[7],
        end_side: darts[2],
        outer_loop: darts[0],
    })
}

fn sew_revolved_faces<P: Payload>(
    g: &mut GMap<P>,
    faces: &[RevolvedFace],
    close_ring: bool,
) -> Result<(), RevolveError> {
    for i in 0..faces.len().saturating_sub(1) {
        sew(g, Dim::Two, faces[i].end_side, faces[i + 1].start_side)?;
    }

    if close_ring && !faces.is_empty() {
        sew(
            g,
            Dim::Two,
            faces[faces.len() - 1].end_side,
            faces[0].start_side,
        )?;
    }

    Ok(())
}

fn revolve_circle_curve(axis: Axis3, point: Point3) -> Curve {
    let projected = axis.project(point);
    let radius = distance(&projected, &point);
    if radius <= LINEAR_TOLERANCE {
        return Curve::Circle(Circle::from_axis(
            Axis3::new(projected, axis.direction),
            radius,
        ));
    }

    Curve::Circle(Circle::new(
        Plane::new(projected, point - projected, axis.direction),
        radius,
    ))
}

fn quad_pcurves(uv: &[(Point2, Point2); 4], darts: &[Dart]) -> HashMap<Dart, Curve2> {
    let mut pcurves = HashMap::with_capacity(4);
    for i in 0..4 {
        pcurves.insert(darts[2 * i], Curve2::Line(Line2::new(uv[i].0, uv[i].1)));
    }
    pcurves
}

pub fn add_revolved_face<P: Payload>(
    g: &mut GMap<P>,
    face_key: FaceKey,
    axis: Axis3,
    angle: Rad64,
) -> Result<SolidKey, RevolveError> {
    let angle = angle.clamp(Angle::ZERO, Angle::FULL_TURN);
    let face = g
        .face(face_key)
        .map(|attr| attr.face(g))
        .ok_or(RevolveError::MissingFace { key: face_key })?;
    let mut loops = Vec::with_capacity(1 + face.inner_loops().len());
    loops.push(face.outer_loop().dart);
    loops.extend(face.inner_loops().into_iter().map(|loop_| loop_.dart));

    if is_full_turn(angle) {
        return add_full_revolved_face(g, loops, axis, angle);
    }

    let rotated_face = rotate_face(&face, axis, angle)?;
    let top_face_dart = g.merge(rotated_face.face());
    let top_face_key = *g
        .attribute::<Cell2>(top_face_dart)
        .expect("merged rotated face should preserve its face attribute");
    let top_face_attr = g
        .face(top_face_key)
        .expect("merged rotated face key should remain valid");
    let mut top_loops = Vec::with_capacity(1 + top_face_attr.inner_loops.len());
    top_loops.push(top_face_attr.outer_loop);
    top_loops.extend(top_face_attr.inner_loops.iter().copied());

    let mut shell = None;
    for (bottom_loop, top_loop) in loops.into_iter().zip(top_loops) {
        let revolved = sew_revolved_loop_to_caps(g, bottom_loop, top_loop, axis, angle)?;
        shell.get_or_insert(revolved);
    }

    let shell = shell.expect("a face should have at least one boundary loop");
    Ok(g.add_solid(SolidAttr::new(P::S::default(), shell, None)))
}

fn add_full_revolved_face<P: Payload>(
    g: &mut GMap<P>,
    loops: Vec<Dart>,
    axis: Axis3,
    angle: Rad64,
) -> Result<SolidKey, RevolveError> {
    let mut shell = None;
    for loop_dart in loops {
        let revolved = add_revolved_profile(g, loop_dart, axis, angle)?;
        shell.get_or_insert(revolved);
    }

    let shell = shell.expect("a face should have at least one boundary loop");
    Ok(g.add_solid(SolidAttr::new(P::S::default(), shell, None)))
}

fn sew_revolved_loop_to_caps<P: Payload>(
    g: &mut GMap<P>,
    bottom_loop: Dart,
    top_loop: Dart,
    axis: Axis3,
    angle: Rad64,
) -> Result<Dart, RevolveError> {
    let bottom_edges = Profile::new(g, bottom_loop)
        .edges()
        .into_iter()
        .map(|edge| edge.dart)
        .collect::<Vec<_>>();
    let top_edges = Profile::new(g, top_loop)
        .edges()
        .into_iter()
        .map(|edge| edge.dart)
        .collect::<Vec<_>>();
    let revolved = add_revolved_profile_faces(g, bottom_loop, axis, angle, true)?;

    for (&cap_edge, &side_edge) in bottom_edges.iter().zip(revolved.bottom_edges.iter()) {
        sew(g, Dim::Two, side_edge, cap_edge)?;
    }
    for (&cap_edge, &side_edge) in top_edges.iter().zip(revolved.top_edges.iter()) {
        sew(g, Dim::Two, side_edge, cap_edge)?;
    }

    Ok(g.cell_representative(revolved.swept_dart, Dim::Three))
}

fn rotate_face<P: Payload>(
    face: &Face<'_, P>,
    axis: Axis3,
    angle: Rad64,
) -> Result<Shape<FaceShape, P>, RevolveError> {
    let (mut rotated, rotated_dart) = face.isolate();

    let vertex_keys = rotated
        .iter_vertices()
        .map(|(key, _)| key)
        .collect::<Vec<_>>();
    for key in vertex_keys {
        let vertex = rotated
            .vertex_mut(key)
            .expect("collected vertex key must remain valid");
        vertex.point = rotate_point(axis, vertex.point, angle);
    }

    let edge_keys = rotated.iter_edges().map(|(key, _)| key).collect::<Vec<_>>();
    for key in edge_keys {
        let edge = rotated
            .edge_mut(key)
            .expect("collected edge key must remain valid");
        edge.curve = rotate_curve(edge.dart, &edge.curve, axis, angle)?;
    }

    let rotated_face_key = *rotated
        .attribute::<Cell2>(rotated_dart)
        .expect("isolating a face must preserve its face attribute");
    let rotated_face = rotated
        .face_mut(rotated_face_key)
        .expect("isolated face key must remain valid");
    rotated_face.surface =
        rotate_surface(rotated_face.outer_loop, &rotated_face.surface, axis, angle)?;

    Ok(Shape::new(rotated, rotated_face_key))
}

fn rotate_surface(
    dart: Dart,
    surface: &Surface,
    axis: Axis3,
    angle: Rad64,
) -> Result<Surface, RevolveError> {
    match surface {
        Surface::Plane(plane) => {
            let rotation = Rotation3::from_axis_angle(&axis.direction, angle.val());
            Ok(Surface::Plane(Plane::from_xy(
                rotate_point(axis, plane.origin(), angle),
                rotation * *plane.x_dir(),
                rotation * *plane.y_dir(),
            )))
        }
        Surface::Cylinder(_) | Surface::Ruled(_) | Surface::Revolution(_) | Surface::Nurbs(_) => {
            Err(RevolveError::UnsupportedPartialRevolveSurface { dart })
        }
    }
}

pub fn face_key_for_dart<P: Payload>(g: &GMap<P>, dart: Dart) -> Option<FaceKey> {
    g.attribute::<Cell2>(dart).copied()
}
