from .. import Solid, StepImport

def write_step(solid: Solid, path: str | None = None, name: str | None = None) -> str: ...
def step_to_string(solid: Solid, name: str | None = None) -> str: ...
def read_step(path: str, strict: bool = False) -> StepImport: ...
def step_from_string(text: str, strict: bool = False) -> StepImport: ...
