def to_tcv(obj: object, name: str | None = None, color: str = "#e8b024", alpha: float = 1.0) -> dict: ...
def show(obj: object, name: str | None = None, port: int | None = None, color: str = "#e8b024", alpha: float = 1.0, **viewer_config) -> object: ...
