from typing import Optional
from . import exchange, geometry, modeling

def block(x: float, y: float, z: float, frame: Frame | None = None) -> Solid: ...
def cylinder(radius: float, height: float, frame: Frame | None = None) -> Solid: ...
def sphere(radius: float, frame: Frame | None = None) -> Solid: ...
def torus(major: float, minor: float, frame: Frame | None = None) -> Solid: ...
def fuse(first: Solid, second: Solid) -> Solid: ...
def cut(target: Solid, tool: Solid) -> Solid: ...
def intersect(first: Solid, second: Solid) -> Solid: ...
def line(start: tuple[float, float, float], end: tuple[float, float, float]) -> Edge: ...
def arc_edge(plane: Plane, radius: float, start_angle: float, end_angle: float) -> Edge: ...
def circle_edge(plane: Plane, radius: float) -> Edge: ...
def rectangle_profile(x_size: float, y_size: float) -> Profile: ...
def polygon_profile(points: list[tuple[float, float, float]]) -> Profile: ...
def rectangle_face(x_size: float, y_size: float) -> Face: ...
def polygon_face(points: list[tuple[float, float, float]]) -> Face: ...
def circle_face(plane: Plane, radius: float) -> Face: ...
def extrude(face: Face, direction: Vector, distance: float) -> Solid: ...
def write_step(solid: Solid, path: str | None = None, name: str | None = None) -> str: ...
def step_to_string(solid: Solid, name: str | None = None) -> str: ...
def to_tcv(obj: object, name: str | None = None, color: str = "#e8b024", alpha: float = 1.0) -> dict: ...
def show(obj: object, name: str | None = None, port: int | None = None, color: str = "#e8b024", alpha: float = 1.0, **viewer_config) -> object: ...

class Model:
    @staticmethod
    def deserialize(serialized: str) -> Model: ...
    @property
    def dimension(self) -> int: ...
    @property
    def involution_count(self) -> int: ...
    @property
    def dart_count(self) -> int: ...
    def serialize(self) -> str: ...
    def darts(self) -> list[int]: ...
    def alpha(self, dimension: int, dart: int) -> int: ...
    def is_free(self, dimension: int, dart: int) -> bool: ...
    def orbit(self, dart: int, involutions: list[int]) -> list[int]: ...
    def cells(self, dimension: int) -> list[int]: ...
    def cell_darts(self, dart: int, dimension: int) -> list[int]: ...
    def cell_representative(self, dart: int, dimension: int) -> int: ...
    def incident_cells(self, dart: int, container_dimension: int, target_dimension: int) -> list[int]: ...
    def adjacent_cells(self, dart: int, dimension: int) -> list[int]: ...
    def vertices(self) -> list[Vertex]: ...
    def edges(self) -> list[Edge]: ...
    def profiles(self) -> list[Profile]: ...
    def faces(self) -> list[Face]: ...
    def sheets(self) -> list[Sheet]: ...
    def solids(self) -> list[Solid]: ...
    def vertex(self, dart: int) -> Vertex | None: ...
    def edge(self, dart: int) -> Edge | None: ...
    def profile(self, dart: int) -> Profile | None: ...
    def face(self, dart: int) -> Face | None: ...
    def sheet(self, dart: int) -> Sheet | None: ...
    def solid(self, dart: int) -> Solid | None: ...

class Solid:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def outer_shell(self) -> Shell: ...
    @property
    def face_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    def isolated(self) -> Solid: ...
    def inner_shells(self) -> list[Shell]: ...
    def shells(self) -> list[Shell]: ...
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Shell:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Shell: ...

class Sheet:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def is_closed(self) -> bool: ...
    def isolated(self) -> Sheet: ...
    def darts(self) -> list[int]: ...
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Sheet: ...

class Profile:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def start(self) -> Vertex: ...
    @property
    def end(self) -> Vertex: ...
    def isolated(self) -> Profile: ...
    def darts(self) -> list[int]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Profile: ...

class Face:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def surface(self) -> Surface: ...
    @property
    def outer_loop(self) -> Loop: ...
    def isolated(self) -> Face: ...
    def inner_loops(self) -> list[Loop]: ...
    def loops(self) -> list[Loop]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Face: ...

class Loop:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    def darts(self) -> list[int]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Loop: ...

class Edge:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def start(self) -> Vertex: ...
    @property
    def end(self) -> Vertex: ...
    @property
    def length(self) -> Optional[float]: ...
    @property
    def curve(self) -> Optional[Curve]: ...
    def isolated(self) -> Edge: ...
    def darts(self) -> list[int]: ...
    def vertices(self) -> list[Vertex]: ...
    def faces(self) -> list[Face]: ...
    def sheets(self) -> list[Sheet]: ...
    def reversed(self) -> Edge: ...

class Vertex:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def point(self) -> Optional[Point]: ...
    def isolated(self) -> Vertex: ...
    def edges(self) -> list[Edge]: ...
    def faces(self) -> list[Face]: ...
    def sheets(self) -> list[Sheet]: ...

class Point:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

class Vector:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

class Point2:
    def __init__(self, x: float, y: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    def as_tuple(self) -> tuple[float, float]: ...

class Vector2:
    def __init__(self, x: float, y: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    def as_tuple(self) -> tuple[float, float]: ...

class Axis:
    def __init__(self, origin: Point, direction: Vector) -> None: ...
    @staticmethod
    def from_points(start: Point, end: Point) -> Axis: ...
    @property
    def origin(self) -> Point: ...
    @property
    def direction(self) -> Vector: ...
    def project(self, point_to_project: Point) -> Point: ...

class Frame:
    def __init__(self, origin: Point, x_dir: Vector, y_dir: Vector) -> None: ...
    @staticmethod
    def xyz() -> Frame: ...
    @staticmethod
    def from_xy(origin: Point, x_dir: Vector, y_dir: Vector) -> Frame: ...
    @staticmethod
    def from_xz(origin: Point, x_dir: Vector, z_dir: Vector) -> Frame: ...
    @property
    def origin(self) -> Point: ...
    @property
    def x_dir(self) -> Vector: ...
    @property
    def y_dir(self) -> Vector: ...
    @property
    def z_dir(self) -> Vector: ...
    @property
    def x_axis(self) -> Axis: ...
    @property
    def y_axis(self) -> Axis: ...
    @property
    def z_axis(self) -> Axis: ...
    def point_at(self, coordinates: Vector) -> Point: ...
    def coordinates_of(self, point_to_locate: Point) -> Vector: ...

Curve = Line | Circle | NurbsCurve
Surface = Plane | Cylinder | Sphere | Cone | RuledSurface | SurfaceOfRevolution | NurbsSurface

class Line:
    @property
    def start(self) -> Point: ...
    @property
    def end(self) -> Point: ...
    def point_at(self, t: float) -> Point: ...

class Circle:
    @property
    def plane(self) -> Plane: ...
    @property
    def radius(self) -> float: ...
    def point_at(self, t: float) -> Point: ...

class NurbsCurve:
    @property
    def degree(self) -> int: ...
    @property
    def domain(self) -> tuple[float, float]: ...
    @property
    def knots(self) -> list[float]: ...
    @property
    def control_points(self) -> list[tuple[Point, float]]: ...
    def point_at(self, u: float) -> Point: ...

class Plane:
    def __init__(self, origin: Point, x_dir: Vector, normal: Vector) -> None: ...
    @staticmethod
    def xy() -> Plane: ...
    @staticmethod
    def xz() -> Plane: ...
    @staticmethod
    def yz() -> Plane: ...
    @property
    def origin(self) -> Point: ...
    @property
    def x_dir(self) -> Vector: ...
    @property
    def y_dir(self) -> Vector: ...
    @property
    def normal(self) -> Vector: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...

class Cylinder:
    @property
    def origin(self) -> Point: ...
    @property
    def x_dir(self) -> Vector: ...
    @property
    def axis(self) -> Vector: ...
    @property
    def radius(self) -> float: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...

class Sphere:
    @property
    def origin(self) -> Point: ...
    @property
    def x_dir(self) -> Vector: ...
    @property
    def axis(self) -> Vector: ...
    @property
    def radius(self) -> float: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...

class Cone:
    @property
    def origin(self) -> Point: ...
    @property
    def x_dir(self) -> Vector: ...
    @property
    def axis(self) -> Vector: ...
    @property
    def reference_radius(self) -> float: ...
    @property
    def half_angle(self) -> float: ...
    @property
    def apex_parameter(self) -> float | None: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...

class RuledSurface:
    @property
    def curve(self) -> Curve: ...
    @property
    def direction(self) -> Vector: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...

class SurfaceOfRevolution:
    @property
    def curve(self) -> Curve: ...
    @property
    def origin(self) -> Point: ...
    @property
    def axis(self) -> Vector: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...

class NurbsSurface:
    @property
    def degree_u(self) -> int: ...
    @property
    def degree_v(self) -> int: ...
    @property
    def domain_u(self) -> tuple[float, float]: ...
    @property
    def domain_v(self) -> tuple[float, float]: ...
    @property
    def knots_u(self) -> list[float]: ...
    @property
    def knots_v(self) -> list[float]: ...
    @property
    def control_points(self) -> list[list[tuple[Point, float]]]: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...
