from typing import Optional

def block(x: float, y: float, z: float) -> Solid: ...
def line(start: tuple[float, float, float], end: tuple[float, float, float]) -> Edge: ...
def rectangle_profile(x_size: float, y_size: float) -> Profile: ...
def rectangle_face(x_size: float, y_size: float) -> Face: ...
def to_tcv(obj: object, name: str | None = None, color: str = "#e8b024", alpha: float = 1.0) -> dict: ...
def show(obj: object, name: str | None = None, port: int | None = None, color: str = "#e8b024", alpha: float = 1.0, **viewer_config) -> object: ...

class GMap:
    @staticmethod
    def deserialize(serialized: str) -> GMap: ...
    @property
    def dimension(self) -> int: ...
    @property
    def involution_count(self) -> int: ...
    @property
    def dart_count(self) -> int: ...
    def serialize(self) -> str: ...
    def darts(self) -> list[int]: ...
    def alpha(self, dimension: int, dart: int) -> int: ...
    def is_free(self, dimension: int, dart: int) -> bool: ...
    def orbit(self, dart: int, involutions: list[int]) -> list[int]: ...
    def cells(self, dimension: int) -> list[int]: ...
    def cell_darts(self, dart: int, dimension: int) -> list[int]: ...
    def cell_representative(self, dart: int, dimension: int) -> int: ...
    def incident_cells(self, dart: int, container_dimension: int, target_dimension: int) -> list[int]: ...
    def adjacent_cells(self, dart: int, dimension: int) -> list[int]: ...
    def vertices(self) -> list[Vertex]: ...
    def edges(self) -> list[Edge]: ...
    def profiles(self) -> list[Profile]: ...
    def faces(self) -> list[Face]: ...
    def sheets(self) -> list[Sheet]: ...
    def solids(self) -> list[Solid]: ...
    def vertex(self, dart: int) -> Vertex | None: ...
    def edge(self, dart: int) -> Edge | None: ...
    def profile(self, dart: int) -> Profile | None: ...
    def face(self, dart: int) -> Face | None: ...
    def sheet(self, dart: int) -> Sheet | None: ...
    def solid(self, dart: int) -> Solid | None: ...

class Solid:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def outer_shell(self) -> Shell: ...
    @property
    def face_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    def inner_shells(self) -> list[Shell]: ...
    def shells(self) -> list[Shell]: ...
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Shell:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Shell: ...

class Sheet:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def is_closed(self) -> bool: ...
    def darts(self) -> list[int]: ...
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Sheet: ...

class Profile:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def start(self) -> Vertex: ...
    @property
    def end(self) -> Vertex: ...
    def darts(self) -> list[int]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Profile: ...

class Face:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def surface(self) -> Surface: ...
    @property
    def outer_loop(self) -> Loop: ...
    def inner_loops(self) -> list[Loop]: ...
    def loops(self) -> list[Loop]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Face: ...

class Loop:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    def darts(self) -> list[int]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...
    def reversed(self) -> Loop: ...

class Edge:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def start(self) -> Vertex: ...
    @property
    def end(self) -> Vertex: ...
    @property
    def length(self) -> Optional[float]: ...
    @property
    def curve(self) -> Optional[Curve]: ...
    def darts(self) -> list[int]: ...
    def vertices(self) -> list[Vertex]: ...
    def faces(self) -> list[Face]: ...
    def sheets(self) -> list[Sheet]: ...
    def reversed(self) -> Edge: ...

class Vertex:
    @property
    def gmap(self) -> GMap: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    @property
    def point(self) -> Optional[Point3]: ...
    def edges(self) -> list[Edge]: ...
    def faces(self) -> list[Face]: ...
    def sheets(self) -> list[Sheet]: ...

class Point3:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

class Vector3:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

Curve = Line | Circle | NurbsCurve
Surface = Plane | Cylinder | RuledSurface | SurfaceOfRevolution | NurbsSurface

class Line:
    @property
    def start(self) -> Point3: ...
    @property
    def end(self) -> Point3: ...
    def point_at(self, t: float) -> Point3: ...

class Circle:
    @property
    def plane(self) -> Plane: ...
    @property
    def radius(self) -> float: ...
    def point_at(self, t: float) -> Point3: ...

class NurbsCurve:
    @property
    def degree(self) -> int: ...
    @property
    def domain(self) -> tuple[float, float]: ...
    @property
    def knots(self) -> list[float]: ...
    @property
    def control_points(self) -> list[tuple[Point3, float]]: ...
    def point_at(self, u: float) -> Point3: ...

class Plane:
    @property
    def origin(self) -> Point3: ...
    @property
    def x_dir(self) -> Vector3: ...
    @property
    def y_dir(self) -> Vector3: ...
    @property
    def normal(self) -> Vector3: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class Cylinder:
    @property
    def origin(self) -> Point3: ...
    @property
    def x_dir(self) -> Vector3: ...
    @property
    def axis(self) -> Vector3: ...
    @property
    def radius(self) -> float: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class RuledSurface:
    @property
    def curve(self) -> Curve: ...
    @property
    def direction(self) -> Vector3: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class SurfaceOfRevolution:
    @property
    def curve(self) -> Curve: ...
    @property
    def origin(self) -> Point3: ...
    @property
    def axis(self) -> Vector3: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...

class NurbsSurface:
    @property
    def degree_u(self) -> int: ...
    @property
    def degree_v(self) -> int: ...
    @property
    def domain_u(self) -> tuple[float, float]: ...
    @property
    def domain_v(self) -> tuple[float, float]: ...
    @property
    def knots_u(self) -> list[float]: ...
    @property
    def knots_v(self) -> list[float]: ...
    @property
    def control_points(self) -> list[list[tuple[Point3, float]]]: ...
    def point_at(self, u: float, v: float) -> Point3: ...
    def normal_at(self, u: float, v: float) -> Vector3: ...
