"""Native NGK bindings used by the structured Python facade."""

from typing import Any, Optional, TypeAlias

class Model:
    @staticmethod
    def deserialize(serialized: str) -> Model: ...
    def serialize(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    @property
    def involution_count(self) -> int: ...
    @property
    def dart_count(self) -> int: ...
    def darts(self) -> list[int]: ...
    def alpha(self, dimension: int, dart: int) -> int: ...
    def cells(self, dimension: int) -> list[int]: ...
    def cell_darts(self, dart: int, dimension: int) -> list[int]: ...
    def cell_representative(self, dart: int, dimension: int) -> int: ...
    def vertices(self) -> list[Vertex]: ...
    def edges(self) -> list[Edge]: ...
    def profiles(self) -> list[Profile]: ...
    def faces(self) -> list[Face]: ...
    def sheets(self) -> list[Sheet]: ...
    def solids(self) -> list[Solid]: ...

class _Topology:
    @property
    def model(self) -> Model: ...
    @property
    def key(self) -> str: ...
    @property
    def dart_id(self) -> int: ...
    def isolated(self) -> Any: ...
    def reversed(self) -> Any: ...

class Vertex(_Topology):
    @property
    def point(self) -> Optional[Point]: ...
    def edges(self) -> list[Edge]: ...
    def faces(self) -> list[Face]: ...

class Edge(_Topology):
    @property
    def start(self) -> Vertex: ...
    @property
    def end(self) -> Vertex: ...
    @property
    def length(self) -> Optional[float]: ...
    @property
    def curve(self) -> Optional[Curve]: ...
    def vertices(self) -> list[Vertex]: ...
    def faces(self) -> list[Face]: ...

class Profile(_Topology):
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Loop(_Topology):
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Face(_Topology):
    @property
    def surface(self) -> Surface: ...
    @property
    def outer_loop(self) -> Loop: ...
    def loops(self) -> list[Loop]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Sheet(_Topology):
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...

class Shell(_Topology):
    def faces(self) -> list[Face]: ...

class Solid(_Topology):
    @property
    def outer_shell(self) -> Shell: ...
    @property
    def face_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    def shells(self) -> list[Shell]: ...
    def faces(self) -> list[Face]: ...
    def edges(self) -> list[Edge]: ...
    def vertices(self) -> list[Vertex]: ...

class Point:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

class Vector:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def as_tuple(self) -> tuple[float, float, float]: ...

class Point2:
    def __init__(self, x: float, y: float) -> None: ...
    def as_tuple(self) -> tuple[float, float]: ...

class Vector2(Point2): ...

class Axis:
    def __init__(self, origin: Point, direction: Vector) -> None: ...

class Frame:
    @staticmethod
    def xyz() -> Frame: ...
    @staticmethod
    def from_xy(origin: Point, x_dir: Vector, y_dir: Vector) -> Frame: ...
    @staticmethod
    def from_xz(origin: Point, x_dir: Vector, z_dir: Vector) -> Frame: ...

class Line: ...
class Circle: ...
class Ellipse: ...
class NurbsCurve: ...
class Plane:
    def __init__(self, origin: Point, x_dir: Vector, normal: Vector) -> None: ...
    @staticmethod
    def xy() -> Plane: ...
    @staticmethod
    def xz() -> Plane: ...
    @staticmethod
    def yz() -> Plane: ...
    @property
    def origin(self) -> Point: ...
    @property
    def x_dir(self) -> Vector: ...
    @property
    def y_dir(self) -> Vector: ...
    @property
    def normal(self) -> Vector: ...
    def point_at(self, u: float, v: float) -> Point: ...
    def normal_at(self, u: float, v: float) -> Vector: ...
class Cylinder: ...
class Sphere: ...
class Cone: ...
class Torus: ...
class RuledSurface: ...
class SurfaceOfRevolution: ...
class NurbsSurface: ...

Curve: TypeAlias = Line | Circle | NurbsCurve
Surface: TypeAlias = Plane | Cylinder | Sphere | Cone | RuledSurface | SurfaceOfRevolution | NurbsSurface

class StepImport:
    solids: list[Solid]
    skipped: list[str]

def read_step(path: str) -> StepImport: ...
def step_from_string(text: str) -> StepImport: ...
def step_to_string(solid: Solid, name: str | None = None) -> str: ...
def write_step(solid: Solid, path: str | None = None, name: str | None = None) -> str: ...
def _to_tcv_json(obj: object, name: str | None = None, color: str = "#e8b024", alpha: float = 1.0) -> str: ...
