use crate::topology::closed::Closed;
use crate::topology::gmap::Dim;
use crate::topology::profile::{Loop, Profile};
use crate::topology::shape_keys::FacetKey;

use super::edge::Edge;
use super::face::Face;
use super::gmap::{Dart, GMap, MergeTopology, TopologyMerge};
use super::payload::{Payload, StandardPayload};
use super::vertex::Vertex;

/// A raw gmap 2-cell view.
///
/// A facet is the orbit generated by every alpha except alpha2. A domain
/// [`Face`] uses one or more oriented facet loops, while the shared geometry is
/// identified by [`FacetKey`].
pub struct Facet<'a, P: Payload = StandardPayload> {
    gmap: &'a GMap<P>,
    /// A dart belonging to this facet's 2-cell orbit.
    pub dart: Dart,
}

impl<'a, P: Payload> Clone for Facet<'a, P> {
    fn clone(&self) -> Self {
        Self {
            gmap: self.gmap,
            dart: self.dart,
        }
    }
}

impl<'a, P: Payload> Facet<'a, P> {
    /// Creates a facet view rooted at `dart`.
    pub fn new(gmap: &'a GMap<P>, dart: Dart) -> Self {
        Self { gmap, dart }
    }

    /// Iterates every dart of this facet's 2-cell orbit.
    pub fn darts(&self) -> impl Iterator<Item = Dart> + '_ {
        self.gmap
            .orbit(self.dart, self.gmap.orbit_indices(Dim::Two))
    }

    /// Returns the shared geometric facet key attached to this 2-cell.
    ///
    /// # Panics
    ///
    /// Panics if the facet has no registered facet key.
    pub fn key(&self) -> FacetKey {
        let dart = self.gmap.cell_representative(self.dart, Dim::Two);
        self.gmap.dart_to_facet[&dart]
    }

    /// Returns this facet as a single closed profile loop.
    ///
    /// `loop` is a Rust keyword, so callers use raw-identifier syntax:
    /// `facet.r#loop()`.
    pub fn r#loop(&self) -> Loop<'a, P> {
        Closed::new_unchecked(Profile::new(self.gmap, self.dart))
    }

    /// Returns the distinct vertices incident to this facet.
    pub fn vertices(&self) -> Vec<Vertex<'a, P>> {
        self.gmap
            .incident_cells(self.dart, Dim::Two, Dim::Zero)
            .map(|d| Vertex::new(self.gmap, d))
            .collect()
    }

    /// Returns this facet's boundary edges in loop traversal order.
    ///
    /// This matches `r#loop().edges()` and therefore has the same
    /// orientation and order as the facet boundary loop.
    pub fn edges(&self) -> Vec<Edge<'a, P>> {
        self.r#loop().edges()
    }

    /// Returns the distinct edge cells incident to this facet.
    ///
    /// This is the raw incidence query between the facet's 2-cell and edge
    /// 1-cells. Use [`Facet::edges`] when boundary-loop order matters.
    pub fn incident_edges(&self) -> Vec<Edge<'a, P>> {
        self.gmap
            .incident_cells(self.dart, Dim::Two, Dim::One)
            .map(|d| Edge::new(self.gmap, d))
            .collect()
    }

    /// Returns the oriented face occurrence using this side of the facet.
    pub fn face(&self) -> Option<Face<'a, P>> {
        let key = self.gmap.face_key_at(self.dart)?;
        self.gmap.face(key)
    }
}

impl<P: Payload> MergeTopology<P> for Facet<'_, P> {
    fn merge_topology(&self) -> TopologyMerge<'_, P> {
        TopologyMerge::new(self.gmap, self.darts().collect(), self.dart)
    }
}
