use super::closed::{Closeable, Closed};
use super::edge::Edge;
use super::gmap::{Dart, Dim};
use super::payload::{Payload, StandardPayload};
use super::vertex::Vertex;
use crate::measure::{LinearProperties, MeasureError, linear_properties_for_edges};
use crate::model::{MergeTopology, Model, TopologyMerge};
use crate::topology::embedding::{is_embedded_cell, turn_where};
use crate::topology::shape_keys::ProfileKey;
use std::collections::HashSet;

/// A keyed 1-dimensional connected topology view with a contextual root dart.
///
/// A profile is the connected component generated by alpha0 and alpha1. It is
/// used for open wires and, when closed, for boundary loops. Domain edges and
/// vertices remain keyed, and the profile has its own stable [`ProfileKey`].
/// The view's dart preserves its current traversal orientation.
pub struct Profile<'a, P: Payload = StandardPayload> {
    model: &'a Model<P>,
    key: ProfileKey,
    /// A dart belonging to this profile's alpha0/alpha1 component.
    pub dart: Dart,
}

impl<'a, P: Payload> Clone for Profile<'a, P> {
    fn clone(&self) -> Self {
        Self {
            model: self.model,
            key: self.key,
            dart: self.dart,
        }
    }
}

impl<'a, P: Payload> Profile<'a, P> {
    /// Creates a profile view from its key using the attribute's reference dart.
    pub fn new(model: &'a Model<P>, key: ProfileKey) -> Self {
        let dart = model.profile_attr_unchecked(key).dart;
        Self { model, key, dart }
    }

    /// Creates a profile view from a dart in a registered profile component.
    pub fn from_dart(model: &'a Model<P>, dart: Dart) -> Option<Self> {
        let key = model.profile_key(dart)?;
        Some(Self { model, key, dart })
    }

    /// Returns the canonical dart naming the profile containing `dart`.
    ///
    /// Takes a model rather than a profile because this is what *gives* a dart
    /// its profile: it runs while the dart-to-key index is being built, before
    /// any profile can be viewed.
    ///
    /// # Panics
    ///
    /// Panics on a dart in no profile, which no dart of a map is.
    pub(crate) fn representative(model: &Model<P>, dart: Dart) -> Dart {
        ProfileIterator::component(model, dart)
            .into_iter()
            .min()
            .expect("profile component cannot be empty")
    }

    /// Returns this profile's stable key.
    pub fn key(&self) -> ProfileKey {
        self.key
    }

    /// Returns the same profile with the opposite traversal orientation.
    pub fn reversed(&self) -> Self {
        Self {
            model: self.model,
            key: self.key,
            dart: self.model.alpha(Dim::Zero, self.dart),
        }
    }

    /// Returns the user payload attached to this profile.
    pub fn data(&self) -> &P::Profile {
        self.model.profile_attr_unchecked(self.key).data()
    }

    /// Iterates the darts of this profile in alternating alpha0/alpha1 order.
    ///
    /// For open profiles, iteration stops when the next required alpha link is
    /// free. For closed profiles, iteration stops just before returning to the
    /// starting dart.
    pub fn darts(&self) -> impl Iterator<Item = Dart> + '_ {
        ProfileIterator::new(self.model, self.dart)
    }

    /// Returns the first vertex in this profile's traversal order.
    ///
    /// # Panics
    ///
    /// Panics if the profile contains no darts.
    pub fn start(&self) -> Vertex<'a, P> {
        self.vertices()[0].clone()
    }

    /// Returns the last vertex for an open profile, or the first vertex for a
    /// closed profile.
    ///
    /// # Panics
    ///
    /// Panics if the profile contains no darts.
    pub fn end(&self) -> Vertex<'a, P> {
        if self.is_closed() {
            self.vertices()[0].clone()
        } else {
            self.vertices()[self.vertices().len() - 1].clone()
        }
    }

    /// Returns this profile's edges in traversal order.
    pub fn edges(&self) -> Vec<Edge<'a, P>> {
        self.darts()
            .step_by(2)
            .filter_map(|d| Edge::from_dart(self.model, d))
            .collect()
    }

    /// Returns the sum of the lengths of the profile's edges.
    pub fn length(&self) -> f64 {
        self.edges().into_iter().map(|edge| edge.length()).sum()
    }

    /// Returns length, centroid and centroidal inertia for this profile.
    pub fn linear_properties(&self) -> Result<LinearProperties, MeasureError> {
        linear_properties_for_edges(self.edges())
    }

    /// Returns this profile's vertices in traversal order.
    pub fn vertices(&self) -> Vec<Vertex<'a, P>> {
        self.darts()
            .step_by(2)
            .filter_map(|d| Vertex::from_dart(self.model, d))
            .collect()
    }
}

impl<P: Payload> MergeTopology<P> for Profile<'_, P> {
    fn merge_topology(&self) -> TopologyMerge<'_, P> {
        TopologyMerge::new(self.model, self.darts().collect(), self.dart)
    }
}

impl<'a, P: Payload> Closeable for Profile<'a, P> {
    /// A profile is closed when no dart in it is alpha0-free or alpha1-free.
    fn is_closed(&self) -> bool {
        self.darts().all(|d| {
            !self.model.is_free(d, Dim::Zero) && ProfileIterator::across(self.model, d).is_some()
        })
    }
}

/// One vertex occurrence in an oriented closed profile.
///
/// A corner keeps the two loop-oriented edges incident to the occurrence.
/// This distinguishes repeated occurrences of the same topological vertex in
/// a non-simple loop.
pub struct LoopCorner<'a, P: Payload = StandardPayload> {
    model: &'a Model<P>,
    incoming: Dart,
    outgoing: Dart,
}

impl<'a, P: Payload> LoopCorner<'a, P> {
    /// Creates a corner between the occurrence arriving at it and the one leaving.
    pub(crate) fn new(model: &'a Model<P>, incoming: Dart, outgoing: Dart) -> Self {
        Self {
            model,
            incoming,
            outgoing,
        }
    }

    /// Returns the edge arriving at this corner in loop traversal order.
    pub fn incoming(&self) -> Edge<'a, P> {
        Edge::from_dart(self.model, self.incoming)
            .expect("LoopCorner incoming dart must have an edge")
    }

    /// Returns the edge leaving this corner in loop traversal order.
    pub fn outgoing(&self) -> Edge<'a, P> {
        Edge::from_dart(self.model, self.outgoing)
            .expect("LoopCorner outgoing dart must have an edge")
    }

    /// Returns the vertex at this loop occurrence.
    ///
    /// A corner is where the loop turns, so it is named by the dart the loop
    /// leaves on rather than by either end of an edge — which is what lets a
    /// one-edge loop still have one.
    pub fn vertex(&self) -> Vertex<'a, P> {
        Vertex::from_dart(self.model, self.outgoing)
            .expect("LoopCorner outgoing dart must have a vertex")
    }
}

impl<'a, P: Payload> Closed<Profile<'a, P>> {
    /// Returns the same closed loop with the opposite traversal orientation.
    pub fn reversed(&self) -> Self {
        Closed::new_unchecked(self.inner().reversed())
    }

    /// Returns the loop corners in traversal order.
    ///
    /// Each corner pairs an incoming edge with the following outgoing edge.
    pub fn corners(&self) -> Vec<LoopCorner<'a, P>> {
        let edge_darts: Vec<Dart> = self.darts().step_by(2).collect();
        let count = edge_darts.len();
        if count == 0 {
            return Vec::new();
        }

        edge_darts
            .iter()
            .enumerate()
            .map(|(index, outgoing_dart)| LoopCorner {
                model: self.model,
                incoming: edge_darts[(index + count - 1) % count],
                outgoing: *outgoing_dart,
            })
            .collect()
    }
}

/// Walks a profile: along the current edge with `alpha0`, then across to the
/// next edge, alternating.
///
/// "Across" is `alpha1` *turned over any raw edge a face owns* — a bridge to a
/// hole, a periodic seam. That single difference is what separates a profile
/// from the raw `alpha0`/`alpha1` component, and it lives here so that one
/// place knows how a profile is walked.
pub(crate) struct ProfileIterator<'a, P: Payload = StandardPayload> {
    model: &'a Model<P>,
    previous: Option<Dart>,
    /// Whether the next move runs along the current edge rather than across to
    /// the next one.
    along_edge: bool,
    /// Every dart already yielded.
    ///
    /// Stopping at the dart the walk started from is not enough on its own. A
    /// walk entered on a bridge leaves along a rim and comes back round to the
    /// rim, never to the bridge, so the only reliable end is a dart repeating.
    seen: HashSet<Dart>,
    start: Dart,
}

impl<'a, P: Payload> ProfileIterator<'a, P> {
    pub(crate) fn new(model: &'a Model<P>, start: Dart) -> Self {
        Self {
            model,
            previous: None,
            along_edge: true,
            seen: HashSet::new(),
            start,
        }
    }

    /// The next edge of the profile at `dart`: `alpha1`, turning across a raw
    /// edge a face owns rather than onto it.
    ///
    /// `None` at a free end, and where the whole fan is scaffold.
    pub(crate) fn across(model: &Model<P>, dart: Dart) -> Option<Dart> {
        turn_where(model.topology(), Dim::One, dart, |at| {
            is_embedded_cell(model.topology(), model.embedding(), Dim::One, at)
        })
    }

    /// Every dart of the profile containing `dart`, in no particular order.
    ///
    /// Deliberately *not* [`Profile::darts`]. That walks forward from the
    /// view's own dart, which is the order its edges and vertices come out in,
    /// and on an open chain entered part way along it reaches only one end.
    /// Identity must not depend on where a walk started, so this one runs both
    /// ways and is the only thing a representative may be read from.
    pub(crate) fn component(model: &Model<P>, dart: Dart) -> Vec<Dart> {
        let mut seen = HashSet::new();
        let mut darts = Vec::new();
        // Forward from the dart reaches one end of an open chain, and forward
        // from the far end of its own edge reaches the other. A closed chain
        // comes back either way, so the second walk then adds nothing.
        for from in [dart, model.alpha(Dim::Zero, dart)] {
            for walked in ProfileIterator::new(model, from) {
                if seen.insert(walked) {
                    darts.push(walked);
                }
            }
        }
        darts
    }
}

impl<'a, P: Payload> Iterator for ProfileIterator<'a, P> {
    type Item = Dart;

    fn next(&mut self) -> Option<Self::Item> {
        let current = match self.previous {
            None => self.start,
            Some(previous) => {
                let next = if self.along_edge {
                    (!self.model.is_free(previous, Dim::Zero))
                        .then(|| self.model.alpha(Dim::Zero, previous))
                } else {
                    Self::across(self.model, previous)
                }?;
                self.along_edge = !self.along_edge;
                next
            }
        };

        if !self.seen.insert(current) {
            return None;
        }
        self.previous = Some(current);
        Some(current)
    }
}
