use super::closed::{Closeable, Closed};
use super::edge::Edge;
use super::gmap::{Dart, Dim, GMap, MergeTopology, TopologyMerge};
use super::payload::{Payload, StandardPayload};
use super::vertex::Vertex;
use crate::topology::shape_keys::ProfileKey;

/// A dart-rooted 1-dimensional connected topology view.
///
/// A profile is the connected component generated by alpha0 and alpha1. It is
/// used for open wires and, when closed, for boundary loops. Domain edges and
/// vertices remain keyed; the profile itself is identified by a representative
/// dart.
pub struct Profile<'a, P: Payload = StandardPayload> {
    gmap: &'a GMap<P>,
    key: ProfileKey,
    /// A dart belonging to this profile's alpha0/alpha1 component.
    pub dart: Dart,
}

impl<'a, P: Payload> Clone for Profile<'a, P> {
    fn clone(&self) -> Self {
        Self {
            gmap: self.gmap,
            key: self.key,
            dart: self.dart,
        }
    }
}

impl<'a, P: Payload> Profile<'a, P> {
    /// Creates a profile view from its key using the attribute's reference dart.
    pub fn new(gmap: &'a GMap<P>, key: ProfileKey) -> Self {
        let dart = gmap.profile_attr_unchecked(key).dart;
        Self { gmap, key, dart }
    }

    /// Creates a profile view from a dart in a registered profile component.
    pub fn from_dart(gmap: &'a GMap<P>, dart: Dart) -> Option<Self> {
        let key = gmap.profile_key(dart)?;
        Some(Self { gmap, key, dart })
    }

    /// Returns this profile's stable key.
    pub fn key(&self) -> ProfileKey {
        self.key
    }

    /// Returns the user payload attached to this profile.
    pub fn data(&self) -> &P::Profile {
        &self.gmap.profile_attr_unchecked(self.key).data
    }

    /// Iterates the darts of this profile in alternating alpha0/alpha1 order.
    ///
    /// For open profiles, iteration stops when the next required alpha link is
    /// free. For closed profiles, iteration stops just before returning to the
    /// starting dart.
    pub fn darts(&self) -> impl Iterator<Item = Dart> + '_ {
        LoopIterator::new(self.gmap, self.dart)
    }

    /// Returns the first vertex in this profile's traversal order.
    ///
    /// # Panics
    ///
    /// Panics if the profile contains no darts.
    pub fn start(&self) -> Vertex<'a, P> {
        self.vertices()[0].clone()
    }

    /// Returns the last vertex for an open profile, or the first vertex for a
    /// closed profile.
    ///
    /// # Panics
    ///
    /// Panics if the profile contains no darts.
    pub fn end(&self) -> Vertex<'a, P> {
        if self.is_closed() {
            self.vertices()[0].clone()
        } else {
            self.vertices()[self.vertices().len() - 1].clone()
        }
    }

    /// Returns this profile's edges in traversal order.
    pub fn edges(&self) -> Vec<Edge<'a, P>> {
        self.darts()
            .step_by(2)
            .filter_map(|d| Edge::from_dart(self.gmap, d))
            .collect()
    }

    /// Returns this profile's vertices in traversal order.
    pub fn vertices(&self) -> Vec<Vertex<'a, P>> {
        self.darts()
            .step_by(2)
            .filter_map(|d| Vertex::from_dart(self.gmap, d))
            .collect()
    }
}

impl<P: Payload> MergeTopology<P> for Profile<'_, P> {
    fn merge_topology(&self) -> TopologyMerge<'_, P> {
        TopologyMerge::new(self.gmap, self.darts().collect(), self.dart)
    }
}

impl<'a, P: Payload> Closeable for Profile<'a, P> {
    /// A profile is closed when no dart in it is alpha0-free or alpha1-free.
    fn is_closed(&self) -> bool {
        self.darts()
            .all(|d| !self.gmap.is_free(d, Dim::Zero) && !self.gmap.is_free(d, Dim::One))
    }
}

/// A closed profile used as a face boundary loop.
///
/// The closedness invariant is checked by [`Closed::new`] or trusted by
/// [`Closed::new_unchecked`].
pub type Loop<'a, P = StandardPayload> = Closed<Profile<'a, P>>;

/// One vertex occurrence in an oriented closed profile.
///
/// A corner keeps the two loop-oriented edges incident to the occurrence.
/// This distinguishes repeated occurrences of the same topological vertex in
/// a non-simple loop.
pub struct LoopCorner<'a, P: Payload = StandardPayload> {
    gmap: &'a GMap<P>,
    incoming: Dart,
    outgoing: Dart,
}

impl<'a, P: Payload> LoopCorner<'a, P> {
    /// Returns the edge arriving at this corner in loop traversal order.
    pub fn incoming(&self) -> Edge<'a, P> {
        Edge::from_dart(self.gmap, self.incoming)
            .expect("LoopCorner incoming dart must have an edge")
    }

    /// Returns the edge leaving this corner in loop traversal order.
    pub fn outgoing(&self) -> Edge<'a, P> {
        Edge::from_dart(self.gmap, self.outgoing)
            .expect("LoopCorner outgoing dart must have an edge")
    }

    /// Returns the vertex at this loop occurrence.
    pub fn vertex(&self) -> Vertex<'a, P> {
        self.outgoing().start()
    }
}

impl<'a, P: Payload> Closed<Profile<'a, P>> {
    /// Returns the loop corners in traversal order.
    ///
    /// Each corner pairs an incoming edge with the following outgoing edge.
    pub fn corners(&self) -> Vec<LoopCorner<'a, P>> {
        let edge_darts: Vec<Dart> = self.darts().step_by(2).collect();
        let count = edge_darts.len();
        if count == 0 {
            return Vec::new();
        }

        edge_darts
            .iter()
            .enumerate()
            .map(|(index, outgoing_dart)| LoopCorner {
                gmap: self.gmap,
                incoming: edge_darts[(index + count - 1) % count],
                outgoing: *outgoing_dart,
            })
            .collect()
    }
}

enum LoopInvolution {
    A0,
    A1,
}
impl LoopInvolution {
    fn next(&self) -> Self {
        match self {
            LoopInvolution::A0 => LoopInvolution::A1,
            LoopInvolution::A1 => LoopInvolution::A0,
        }
    }
}

struct LoopIterator<'a, P: Payload = StandardPayload> {
    start: Dart,
    previous: Option<Dart>,
    inv: LoopInvolution,
    gmap: &'a GMap<P>,
}

impl<'a, P: Payload> LoopIterator<'a, P> {
    pub fn new(gmap: &'a GMap<P>, start: Dart) -> Self {
        Self {
            start,
            previous: None,
            inv: LoopInvolution::A0,
            gmap,
        }
    }
}

impl<'a, P: Payload> Iterator for LoopIterator<'a, P> {
    type Item = Dart;

    fn next(&mut self) -> Option<Self::Item> {
        let current = match self.previous {
            None => self.start,
            Some(d) => {
                let dim = match self.inv {
                    LoopInvolution::A0 => Dim::Zero,
                    LoopInvolution::A1 => Dim::One,
                };
                if self.gmap.is_free(d, dim) {
                    return None;
                }
                self.inv = self.inv.next();
                self.gmap.alpha(dim, d)
            }
        };

        if self.previous.is_some() && current == self.start {
            None
        } else {
            self.previous = Some(current);
            Some(current)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{Closeable, Profile};
    use crate::builders::edges::add_edge;
    use crate::geometry::{Curve, Point3};
    use crate::topology::gmap::{Dim, GMap};
    use crate::topology::payload::StandardPayload;

    #[test]
    fn open_profile_darts_include_free_endpoints() {
        let mut g = GMap::<StandardPayload>::new();
        let points = [
            Point3::new(0.0, 0.0, 0.0),
            Point3::new(1.0, 0.0, 0.0),
            Point3::new(1.0, 1.0, 0.0),
        ];

        let first_edge = add_edge(
            &mut g,
            points[0],
            points[1],
            Curve::line(points[0], points[1]),
        )
        .expect("first edge should build");
        let second_edge = add_edge(
            &mut g,
            points[1],
            points[2],
            Curve::line(points[1], points[2]),
        )
        .expect("second edge should build");

        let first_start = g.edge_attr_unchecked(first_edge).dart;
        let first_end = g.alpha(Dim::Zero, first_start);
        let second_start = g.edge_attr_unchecked(second_edge).dart;
        g.sew(Dim::One, first_end, second_start)
            .expect("adjacent open profile edges should be alpha1-sewable");

        let profile_key = g.add_profile(crate::topology::attributes::ProfileAttr::new(
            first_start,
            (),
        ));
        let profile = Profile::new(&g, profile_key);
        let darts = profile.darts().collect::<Vec<_>>();

        assert_eq!(darts.len(), 4);
        assert_eq!(profile.edges().len(), 2);
        assert!(!profile.is_closed());
    }
}
